<?php
$this->scripto()->postTitle($project->title());
$filters = [
    [
        'label' => $this->translate('Is in progress'),
        'value' => 'is_in_progress'
    ],
    [
        'label' => $this->translate('Is new'),
        'value' => 'is_new'
    ],
];
if (!$project->filterApproved()) {
    $filters[] = [
        'label' => $this->translate('Is approved'),
        'value' => 'is_approved'
    ];
    $filters[] = [
        'label' => $this->translate('Is not approved'),
        'value' => 'is_not_approved'
    ];
}
?>
<div class="resource-content">
    <?php if ($projectDescription = $project->description()): ?>
    <div class="project resource-metadata">
        <?php echo $this->escapeHtml($projectDescription); ?>
    </div>
    <?php endif; ?>
    <div class="item resource-list">
        <h3><?php echo $this->scripto()->translate($project->itemType(), 'Items'); ?></h3>
        <div class="media list-head">
            <?php if ($sItems): ?>
            <div class="list-layout">
                <span class="layout-label"><?php echo $this->translate('Layout'); ?></span>
                <button class="list" aria-label="<?php echo $this->escapeHtml($this->translate('List')); ?>"<?php echo 'list' === $project->browseLayout() ? ' disabled' : ''; ?>></button>
                <button class="grid" aria-label="<?php echo $this->escapeHtml($this->translate('Grid')); ?>"<?php echo 'list' !== $project->browseLayout() ? ' disabled' : ''; ?>></button>
            </div>
            <?php endif; ?>
            <div class="sorting-toggle">
                <a href="#" class="sorting-heading menu-toggle"><?php echo $this->translate('Sort'); ?></a>
                <?php echo $this->sortSelector([
                    [
                        'label' => $this->translate('ID'),
                        'value' => 'id'
                    ],
                    [
                        'label' => $this->scripto()->translate($project->contentType(), 'Last edited'),
                        'value' => 'edited'
                    ],
                ]); ?>
            </div>
            <div class="filtering-toggle">
                <a href="#" class="filtering-heading menu-toggle"><?php echo $this->translate('Filter'); ?></a>
                <?php echo $this->filterSelector($filters); ?>
            </div>
            <?php echo $this->pagination(); ?>
        </div>
        <?php if ($sItems): ?>
        <table<?php echo 'list' !== $project->browseLayout() ? ' style="display: none"' : ''; ?> class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
            <thead>
                <tr>
                    <th class="title"><?php echo $this->translate('Title'); ?></th>
                    <th class="last-edited"><?php echo $this->scripto()->translate($project->contentType(), 'Last edited'); ?></th>
                    <th class="status"><?php echo $this->translate('Status'); ?></th>
                    <th class="percentage">%</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($sItems as $sItem): ?>
                <?php
                $approvedCount = $sItem->isApprovedMediaCount();
                $totalCount = $sItem->mediaCount();
                $approvedPercentage = $totalCount ? (100 * ($approvedCount / $totalCount)) : 100;
                ?>
                <tr class="resource-row">
                    <td>
                        <div class="title-flex">
                            <?php echo $sItem->linkRaw($this->thumbnail($sItem, 'square', [
                                'title' => $this->scripto()->translate($project->mediaType(), 'Primary media'),
                                'alt' => $this->scripto()->translate($project->mediaType(), 'Primary media'),
                            ]), null, ['class' => 'resource-media']); ?>
                            <?php echo $sItem->link($sItem->item()->displayTitle(), null, ['class' => 'resource-title']); ?>
                        </div>
                    </td>
                    <td>
                        <span class="last-edited"><?php echo $sItem->edited() ? $this->i18n()->dateFormat($sItem->edited(), 'long', 'medium') : $this->scripto()->translate($project->contentType(), 'Not edited'); ?></span>
                    </td>
                    <td>
                        <span class="status"><?php echo $this->translate($sItem->status()); ?></span>
                    </td>
                    <td class="percentage">
                        <span class="total-approved-media"><?php echo number_format($approvedCount); ?></span> / <span class="total-media"><?php echo number_format($totalCount); ?></span>
                        <div class="status-bar">
                            <div class="completion" style="width: <?php echo $approvedPercentage; ?>%"></div>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="resource-grid"<?php echo 'list' === $project->browseLayout() ? ' style="display: none"' : ''; ?>>
            <?php foreach ($sItems as $sItem): ?>
            <?php
            $approvedCount = $sItem->isApprovedMediaCount();
            $totalCount = $sItem->mediaCount();
            $approvedPercentage = $totalCount ? (100 * ($approvedCount / $totalCount)) : 100;
            ?>
            <div class="resource-tile">
                <?php echo $sItem->linkRaw($this->thumbnail($sItem, 'square', [
                    'title' => $this->scripto()->translate($project->mediaType(), 'Primary media'),
                    'alt' => $this->scripto()->translate($project->mediaType(), 'Primary media'),
                ])); ?>
                <h4><?php echo $sItem->link($sItem->item()->displayTitle()) ?></h4>
                <div class="last-edited"><span class="meta-label"><?php echo $this->scripto()->translate($project->contentType(), 'Last edited'); ?></span> <?php echo $sItem->edited() ? $this->i18n()->dateFormat($sItem->edited(), 'long', 'medium') : $this->scripto()->translate($project->contentType(), 'Not edited'); ?></div>
                <div class="status"><span class="meta-label"><?php echo $this->translate('Status'); ?></span> <?php echo $this->translate($sItem->status()); ?></div>
                <div class="percentage">
                    <span class="meta-label"><?php echo $this->scripto()->translate($project->mediaType(), 'Approved medias'); ?></span>
                    <span class="total-approved-media"><?php echo number_format($approvedCount); ?></span> / <span class="total-media"><?php echo number_format($totalCount); ?></span>
                    <div class="status-bar">
                        <div class="completion" style="width: <?php echo $approvedPercentage; ?>%"></div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php else: ?>
        <div class="no-resources">
            <p><?php echo $this->scripto()->translate($project->itemType(), 'No Scripto items found'); ?></p>
        </div>
        <?php endif; ?>
    </div>
</div>
