<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'scripto user browse');
?>

<?php echo $this->pageTitle($this->translate('Users'), 1, $this->translate('Scripto')); ?>

<?php echo $this->scripto()->adminLoginBar(); ?>

<?php echo $this->scripto()->adminBreadcrumbs(); ?>

<div class="browse-controls">
    <?php echo $this->scripto()->mediawikiPagination(); ?>
</div>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Name'); ?></th>
            <th><?php echo $this->translate('MediaWiki groups'); ?></th>
            <th><?php echo $this->translate('Edit count'); ?></th>
            <th class="comment"><?php echo $this->translate('Date created'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><?php echo $this->hyperlink($user['name'], $this->url('admin/scripto-user-contributions', ['user-id' => $user['name']])); ?></td>
            <td><?php echo implode(', ', $user['groups']); ?></td>
            <td><?php echo number_format($user['editcount']); ?></td>
            <td><?php echo $this->i18n()->dateFormat($user['registration'], 'medium', 'short'); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
