<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'scripto user contribution browse');
?>

<?php echo $this->pageTitle($user['name'], 1, $this->translate('Scripto: User'), $this->translate('Contributions')); ?>

<?php echo $this->scripto()->adminLoginBar(); ?>

<?php echo $this->scripto()->adminBreadcrumbs(); ?>

<div class="browse-controls">
    <?php echo $this->scripto()->mediawikiPagination(); ?>
</div>

<?php if ($userCons): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Revision'); ?></th>
            <th></th>
            <th><?php echo $this->translate('Media #'); ?></th>
            <th><?php echo $this->translate('Type'); ?></th>
            <th><?php echo $this->translate('Item'); ?></th>
            <th><?php echo $this->translate('Project'); ?></th>
            <th><?php echo $this->translate('Size'); ?></th>
            <th class="comment"><?php echo $this->translate('Comment'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($userCons as $userCon): ?>
    <?php
    $date = $userCon['timestamp']->format('G:i, j F Y');
    $flags = array_filter([
        $userCon['new'] ? $this->translate('new') : null,
        $userCon['top'] ? $this->translate('current') : null,
    ]);
    $sMedia = isset($userCon['scripto_media']) ? $userCon['scripto_media'] : null;
    $sItem = $sMedia ? $sMedia->scriptoItem() : null;
    $project = $sItem ? $sItem->scriptoProject() : null;
    $isTalk = (1 === $userCon['ns']);
    ?>
        <tr>
            <td>
                <?php echo $sMedia
                ? $this->hyperlink($date, $this->url(
                    $isTalk ? 'admin/scripto-talk-media-id' : 'admin/scripto-media-id',
                    [
                        'project-id' => $project->id(),
                        'item-id' => $sItem->item()->id(),
                        'media-id' => $sMedia->media()->id(),
                        'revision-id' => $userCon['revid'],
                    ]
                ))
                : $date; ?>
                <span class="flags"><?php echo $flags ? sprintf(' (%s)', implode(', ', $flags)) : null; ?></span>
            </td>
            <td>
                <?php echo $sMedia
                ? sprintf(
                    '(%s | %s)',
                    $userCon['parentid']
                        ? $this->hyperlink($this->translate('diff'), $this->url(
                            $isTalk ? 'admin/scripto-talk-revision-compare' : 'admin/scripto-revision-compare',
                            [
                                'project-id' => $project->id(),
                                'item-id' => $sItem->item()->id(),
                                'media-id' => $sMedia->media()->id(),
                                'from-revision-id' => $userCon['parentid'],
                                'to-revision-id' => $userCon['revid'],
                            ]
                        ))
                        : $this->translate('diff'),
                    $this->hyperlink($this->translate('hist'), $this->url(
                        $isTalk ? 'admin/scripto-talk-revision' : 'admin/scripto-revision',
                        [
                            'project-id' => $project->id(),
                            'item-id' => $sItem->item()->id(),
                            'media-id' => $sMedia->media()->id(),
                        ]
                    ))
                )
                : ''; ?>
            </td>
            <td>
                <?php echo $sMedia
                ? $isTalk
                    ? $this->hyperlink(sprintf($this->scripto()->translate($project->mediaType(), 'Media #%s notes'), $sMedia->position()), $sMedia->adminUrl('talk'))
                    : $this->hyperlink(sprintf($this->scripto()->translate($project->mediaType(), 'Media #%s'), $sMedia->position()), $sMedia->adminUrl())
                : $this->translate('n/a'); ?>
            </td>
            <td><?php echo $project ? $this->scripto()->translate($project->itemType(), 'Item') : $this->translate('n/a'); ?></td>
            <td><?php echo $sItem ? $sItem->link($sItem->item()->displayTitle()) : $userCon['title']; ?></td>
            <td><?php echo $project ? $project->link($project->title()) : $this->translate('n/a'); ?></td>
            <td><?php echo sprintf(
                $this->translate('%s bytes (%s)'),
                number_format($userCon['size']),
                sprintf(
                    '<span style="color: %s;">%s%s</span>',
                    0 < $userCon['sizediff'] ? 'green' : (0 > $userCon['sizediff'] ? 'red' : 'inherit'),
                    0 < $userCon['sizediff'] ? '+' : null,
                    number_format($userCon['sizediff'])
                )
            ); ?></td>
            <td><i><?php echo $userCon['parsedcomment']; ?></i></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>
<div class="no-resources">
    <p><?php echo $this->translate('No user contributions found.'); ?></p>
</div>
<?php endif; ?>
