<?php $route = $routeMatch->getMatchedRouteName(); ?>
<div class="breadcrumbs">

    <?php echo $this->hyperlink($this->translate('Project browse'), $this->url('admin/scripto-project')); ?>

    <?php if ('admin/scripto-item' === $route): ?>
    <div class="separator"></div>
    <?php echo $this->translate('Project review'); ?>
    <?php elseif (in_array($route, ['admin/scripto-media', 'admin/scripto-media-id', 'admin/scripto-revision', 'admin/scripto-revision-id', 'admin/scripto-revision-compare'])): ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Project review'), $this->url('admin/scripto-item', [
        'action' => 'browse',
        'project-id' => $routeMatch->getParam('project-id'),
    ])); ?>
    <?php endif; ?>

    <?php if ('admin/scripto-media' === $route): ?>
    <div class="separator"></div>
    <?php echo $this->translate('Item review'); ?>
    <?php elseif (in_array($route, ['admin/scripto-media-id', 'admin/scripto-revision', 'admin/scripto-revision-id', 'admin/scripto-revision-compare'])): ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Item review'), $this->url('admin/scripto-media', [
        'action' => 'browse',
        'project-id' => $routeMatch->getParam('project-id'),
        'item-id' => $routeMatch->getParam('item-id'),
    ])); ?>
    <?php endif; ?>

    <?php if ('admin/scripto-media-id' === $route): ?>
    <div class="separator"></div>
    <?php echo $this->translate('Media review'); ?>
    <?php elseif (in_array($route, ['admin/scripto-revision', 'admin/scripto-revision-id', 'admin/scripto-revision-compare'])): ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Media review'), $this->url('admin/scripto-media-id', [
        'action' => 'show',
        'project-id' => $routeMatch->getParam('project-id'),
        'item-id' => $routeMatch->getParam('item-id'),
        'media-id' => $routeMatch->getParam('media-id'),
    ])); ?>
    <?php endif; ?>

    <?php if ('admin/scripto-revision' === $route): ?>
    <div class="separator"></div>
    <?php echo $this->translate('Revision browse'); ?>
    <?php elseif (in_array($route, ['admin/scripto-revision-id', 'admin/scripto-revision-compare'])): ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Revision browse'), $this->url('admin/scripto-revision', [
        'action' => 'browse',
        'project-id' => $routeMatch->getParam('project-id'),
        'item-id' => $routeMatch->getParam('item-id'),
        'media-id' => $routeMatch->getParam('media-id'),
    ])); ?>
    <?php endif; ?>

    <?php if ('admin/scripto-revision-id' === $routeMatch->getMatchedRouteName()): ?>
    <div class="separator"></div>
    <?php echo $this->translate('Revision show'); ?>
    <?php endif; ?>

    <?php if ('admin/scripto-revision-compare' === $routeMatch->getMatchedRouteName()): ?>
    <div class="separator"></div>
    <?php echo $this->translate('Revision compare'); ?>
    <?php endif; ?>

</div>
