<?php
$this->headScript()->appendFile($this->assetUrl('vendor/panzoom-4.3.1/dist/panzoom.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/common/media.js', 'Scripto'));
?>
<div id="panzoom-container" class="image">
  <div class="zoom-controls">
      <button type="button" id="panzoom-zoom-in" aria-label="<?php echo $this->escapeHtml($this->translate('Zoom in')); ?>" title="<?php echo $this->escapeHtml($this->translate('Zoom in')); ?>"></button>
      <button type="button" id="panzoom-zoom-out" aria-label="<?php echo $this->escapeHtml($this->translate('Zoom out')); ?>" title="<?php echo $this->escapeHtml($this->translate('Zoom out')); ?>"></button>
      <button type="button" id="panzoom-rotate-right" aria-label="<?php echo $this->escapeHtml($this->translate('Rotate right')); ?>" title="<?php echo $this->escapeHtml($this->translate('Rotate right')); ?>"></button>
      <button type="button" id="panzoom-rotate-left" aria-label="<?php echo $this->escapeHtml($this->translate('Rotate left')); ?>" title="<?php echo $this->escapeHtml($this->translate('Rotate left')); ?>"></button>
      <button type="button" id="panzoom-reset"><?php echo $this->translate('Reset'); ?></button>
  </div>
  <div id="panzoom" class="media-render">
    <img src="<?php echo $this->escapeHtml($media->originalUrl()); ?>" id="panzoom-img">
  </div>
</div>
