<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'browse'); 
?>

<?php echo $this->pageTitle($this->translate('Review project'), 1, $this->translate('Scripto'), $project->title()); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <a href="#" class="expand button" aria-label="<?php echo $this->translate('Expand'); ?>"><?php echo $this->translate('Actions'); ?></a>
        <ul class="collapsible">
            <li><a href="#" class="sidebar-content" data-sidebar-selector="#project-metadata"><?php echo $this->translate('View project metadata'); ?></a></li>
            <li><?php echo $project->link($this->translate('Edit project'), 'edit'); ?></li>
            <li><a href="#" class="sidebar-content" data-sidebar-selector="#sync-project"><?php echo $this->translate('Sync project'); ?></a></li>
            <li><a href="#" class="sidebar-content" data-sidebar-selector="#import-project"><?php echo $this->translate('Import project'); ?></a></li>
            <li><a href="#" class="sidebar-content" data-sidebar-selector="#unimport-project"><?php echo $this->translate('Unimport project'); ?></a></li>
        </ul>
    </div>
</div>

<?php echo $this->scriptoBreadcrumbs(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
        [
            'label' => $this->translate('Date synced'),
            'value' => 'synced'
        ],
        [
            'label' => $this->translate('Last edited'),
            'value' => 'edited'
        ],
    ]); ?>
    <?php echo $this->filterSelector([
        [
            'label' => $this->translate('Is approved'),
            'value' => 'is_approved'
        ],
        [
            'label' => $this->translate('Is not approved'),
            'value' => 'is_not_approved'
        ],
    ]); ?>
</div>

<?php if ($sItems): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Item'); ?></th>
            <th><?php echo $this->translate('Date synced'); ?></th>
            <th><?php echo $this->translate('Last edited'); ?></th>
            <th><?php echo $this->translate('Media count'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($sItems as $sItem): ?>
        <tr>
            <td>
                <?php echo $sItem->linkPretty(); ?>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $sItem->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $this->i18n()->dateFormat($sItem->synced()); ?></td>
            <td><?php echo $this->i18n()->dateFormat($sItem->edited()); ?></td>
            <td><?php echo number_format($sItem->mediaCount()); ?></td>
            <td><?php echo $this->translate($sItem->status()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>
<div class="no-resources">
    <p><?php echo sprintf(
        $this->translate('No Scripto items found. %s'),
        sprintf(
            '<a href="%s">%s</a>',
            $this->url('admin/scripto-project-id', ['controller' => 'project', 'action' => 'show-actions'], true),
            $this->translate('Do you need to sync the project?')
        )
    ); ?></p>
</div>
<?php endif; ?>

<div id="project-metadata" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Project metadata'); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Title'); ?></h4>
        <div class="value"><?php echo $this->escapeHtml($project->title()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Description'); ?></h4>
        <div class="value"><?php echo $this->escapeHtml($project->description()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Item set'); ?></h4>
        <?php $itemSet = $project->itemSet(); ?>
        <div class="value"><?php echo $itemSet->link($itemSet->displayTitle()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Property'); ?></h4>
        <?php $property = $project->property(); ?>
        <div class="value"><?php echo sprintf('%s : %s', $property->vocabulary()->label(), $property->label()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Language tag'); ?></h4>
        <div class="value"><?php echo $this->escapeHtml($project->lang()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Date created'); ?></h4>
        <div class="value"><?php echo $this->i18n()->dateFormat($project->created(), 'long', 'medium'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Last synced'); ?></h4>
        <?php $synced = $project->synced(); ?>
        <div class="value"><?php echo $synced ? $this->i18n()->dateFormat($project->synced(), 'long', 'medium') : $this->translate('Not synced'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Last imported'); ?></h4>
        <?php $imported = $project->imported(); ?>
        <div class="value"><?php echo $imported ? $this->i18n()->dateFormat($project->imported(), 'long', 'medium') : $this->translate('Not imported'); ?></div>
    </div>
</div>

<div id="sync-project" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Sync project'); ?></h3>
    <p><?php echo $this->translate('Synchronize this project with the configured item set. Once synchronized, this project will contain every item in the item set. You should synchronize periodically, any time items are added or removed from the item set, and when item media have been added, removed, or reordered.'); ?></p>
    <?php
    $syncForm->setAttribute('action', $this->url('admin/scripto-project-id', ['action' => 'sync'], true));
    echo $this->form($syncForm);
    ?>
</div>


<div id="import-project" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Import project'); ?></h3>
    <p><?php echo $this->translate('Import project transcriptions from MediaWiki into Omeka. This process will aggregate transcriptions from approved Scripto media and save them to their corresponding Omeka items using the configured property and language tag.'); ?></p>
    <p><?php echo sprintf(
        '<span class="error">%s</span>',
        $this->translate('Warning: all existing values matching the configured property and configured language tag will be overwritten or deleted.')
    ); ?></p>
    <?php
    $importForm->setAttribute('action', $this->url('admin/scripto-project-id', ['action' => 'import'], true));
    echo $this->form($importForm);
    ?>
</div>

<div id="unimport-project" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Unimport project'); ?></h3>
    <p><?php echo $this->translate('Unimport project transcriptions from Omeka.'); ?></p>
    <p><?php echo sprintf(
        '<span class="error">%s</span>',
        $this->translate('Warning: all existing values matching the configured property and configured language tag will be deleted.')
    ); ?></p>
    <?php
    $unimportForm->setAttribute('action', $this->url('admin/scripto-project-id', ['action' => 'unimport'], true));
    echo $this->form($unimportForm);
    ?>
</div>
