<?php $this->htmlElement('body')->appendAttribute('class', 'browse'); ?>

<?php echo $this->pageTitle($this->translate('Review project'), 1, $this->translate('Scripto'), $project->title()); ?>

<div id="page-actions">
    <?php if ($project->userIsAllowed('update')): ?>
    <?php echo $project->link($this->translate('Edit project'), 'edit', ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ScriptoProject')->menu(); ?>
</nav>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
        [
            'label' => $this->translate('Date synced'),
            'value' => 'synced'
        ],
        [
            'label' => $this->translate('Last edited'),
            'value' => 'edited'
        ],
    ]); ?>
    <select name="filter">
        <option value="">All</option>
        <option value="is_approved">Is approved</option>
        <option value="is_not_approved">Is not approved</option>
    </select>
</div>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Item title'); ?></th>
            <th><?php echo $this->translate('Date synced'); ?></th>
            <th><?php echo $this->translate('Last edited'); ?></th>
            <th><?php echo $this->translate('Media count'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($sItems as $sItem): ?>
        <tr>
            <td>
                <?php echo $sItem->linkPretty(); ?>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $sItem->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $this->i18n()->dateFormat($sItem->synced()); ?></td>
            <td><?php echo $this->i18n()->dateFormat($sItem->edited()); ?></td>
            <td><?php echo number_format($sItem->mediaCount()); ?></td>
            <td><?php echo $this->translate($sItem->status()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>
