<?php $this->htmlElement('body')->appendAttribute('class', 'show'); ?>

<?php echo $this->pageTitle($this->translate('Review item'), 1, $this->translate('Scripto'), $item->displayTitle()); ?>

<div id="page-actions">
    <?php echo $project->link($this->translate('Review project'), 'show', ['class' => 'button']); ?>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ScriptoItem')->menu(); ?>
</nav>

<div class="property">
    <h4><?php echo $this->translate('Scripto project'); ?></h4>
    <div class="value"><?php echo $project->link($project->title()); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Status'); ?></h4>
    <div class="value"><?php echo $this->translate($sItem->status()); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Date synced'); ?></h4>
    <div class="value"><?php echo $this->i18n()->dateFormat($sItem->synced(), 'long', 'medium'); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Last edited'); ?></h4>
    <?php $edited = $sItem->edited(); ?>
    <div class="value"><?php echo $edited ? $this->i18n()->dateFormat($sItem->edited(), 'long', 'medium') : $this->translate('Not edited'); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Omeka item'); ?></h4>
    <div class="value"><?php echo $item->link($item->displayTitle()); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Omeka item description'); ?></h4>
    <?php $description = $item->displayDescription(); ?>
    <div class="value"><?php echo $description ? nl2br($this->escapeHtml($description)) : $this->translate('No description'); ?></div>
</div>
