<?php $item = $sItem->item(); ?>

<h3><?php echo $sItem->link($item->displayTitle($item->displayTitle())); ?></h3>
<div class="meta-group">
    <h4><?php echo $this->translate('Status'); ?></h4>
    <div class="value"><?php echo $this->translate($sItem->status()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Date synced'); ?></h4>
    <div class="value"><?php echo $this->i18n()->dateFormat($sItem->synced(), 'long', 'medium'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Last edited'); ?></h4>
    <?php $edited = $sItem->edited(); ?>
    <div class="value"><?php echo $edited ? $this->i18n()->dateFormat($sItem->edited(), 'long', 'medium') : $this->translate('Not edited'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Total media count'); ?></h4>
    <div class="value"><?php echo number_format($sItem->mediaCount()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Is approved media count'); ?></h4>
    <div class="value"><?php echo number_format($sItem->isApprovedMediaCount()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Is completed media count'); ?></h4>
    <div class="value"><?php echo number_format($sItem->isCompletedMediaCount()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Is in progress media count'); ?></h4>
    <div class="value"><?php echo number_format($sItem->isEditedMediaCount()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Description'); ?></h4>
    <?php $description = $item->displayDescription(); ?>
    <div class="value"><?php echo $description ? $this->escapeHtml($description) : $this->translate('No description'); ?></div>
</div>
