<?php $this->htmlElement('body')->appendAttribute('class', 'show'); ?>

<?php echo $this->pageTitle($this->translate('Review item'), 1, $this->translate('Scripto'), $item->displayTitle()); ?>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ScriptoItem')->menu(); ?>
</nav>

<div class="property">
    <h4><?php echo $this->translate('Title'); ?></h4>
    <div class="value"><?php echo $item->link($item->displayTitle()); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Description'); ?></h4>
    <?php $description = $item->displayDescription(); ?>
    <div class="value"><?php echo $description ? $this->escapeHtml($description) : $this->translate('No description'); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Date synced'); ?></h4>
    <div class="value"><?php echo $this->i18n()->dateFormat($sItem->synced(), 'long', 'medium'); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Last edited'); ?></h4>
    <?php $edited = $sItem->edited(); ?>
    <div class="value"><?php echo $edited ? $this->i18n()->dateFormat($sItem->edited(), 'long', 'medium') : $this->translate('Not edited'); ?></div>
</div>
