<?php $this->htmlElement('body')->appendAttribute('class', 'browse'); ?>

<?php echo $this->pageTitle($this->translate('Review media'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div id="page-actions">
    <?php echo $sItem->link($this->translate('Review item'), 'show', ['class' => 'button']); ?>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ScriptoMedia')->menu(); ?>
</nav>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Date'); ?></th>
            <th><?php echo $this->translate('User'); ?></th>
            <th><?php echo $this->translate('Size (bytes)'); ?></th>
            <th><?php echo $this->translate('Comment'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($sMedia->pageRevisions() as $revision): ?>
        <tr>
            <td>
                <?php $datetime = new \DateTime($revision['timestamp']); ?>
                <?php echo $this->hyperlink(
                    $datetime->format('G:i, j F Y'),
                    $this->url('admin/scripto-revision-id', ['action' => 'show', 'revision-id' => $revision['revid']], true)
                ); ?>
            </td>
            <td><?php echo $this->escapeHtml($revision['user']); ?></td>
            <td><?php echo $this->escapeHtml($revision['size']); ?></td>
            <td><?php echo $revision['parsedcomment']; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
