<?php $this->htmlElement('body')->appendAttribute('class', 'browse'); ?>

<?php echo $this->pageTitle($this->translate('Review media'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div id="page-actions">
    <?php echo $sItem->link($this->translate('Review item'), 'show', ['class' => 'button']); ?>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ScriptoMedia')->menu(); ?>
</nav>

<?php if ($revisions): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Compare'); ?></th>
            <th><?php echo $this->translate('Date'); ?></th>
            <th><?php echo $this->translate('User'); ?></th>
            <th><?php echo $this->translate('Size'); ?></th>
            <th><?php echo $this->translate('Comment'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php $latestId = $revisions[0]['revid']; ?>
    <?php foreach ($revisions as $index => $revision): ?>
    <?php $childRevision = isset($revisions[$index + 1]) ? $revisions[$index + 1] : null; ?>
        <tr>
            <td><?php echo sprintf(
                '%s | %s',
                $latestId !== $revision['revid']
                    ? $this->hyperlink($this->translate('current'), $this->url('admin/scripto-revision-compare', ['action' => 'compare', 'from-revision-id' => $revision['revid'], 'to-revision-id' => $latestId], true))
                    : $this->translate('current'),
                $childRevision
                    ? $this->hyperlink($this->translate('previous'), $this->url('admin/scripto-revision-compare', ['action' => 'compare', 'from-revision-id' => $childRevision['revid'], 'to-revision-id' => $revision['revid']], true))
                    : $this->translate('previous')
            ); ?></td>
            <td>
                <?php $datetime = new \DateTime($revision['timestamp']); ?>
                <?php echo $this->hyperlink(
                    $datetime->format('G:i, j F Y'),
                    $this->url('admin/scripto-revision-id', ['action' => 'show', 'revision-id' => $revision['revid']], true)
                ); ?>
            </td>
            <td><?php echo $this->escapeHtml($revision['user']); ?></td>
            <td><?php echo sprintf(
                '%s bytes (%s)',
                $revision['size'],
                $childRevision ? sprintf('%+d', $revision['size'] - $childRevision['size']) : sprintf('+%d', $revision['size'])
            ); ?></td>
            <td><?php echo $revision['parsedcomment']; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>
<div class="no-resources">
    <p><?php echo $this->translate('This Scripto media has no revisions.'); ?></p>
</div>
<?php endif; ?>
