<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'browse'); 
?>

<?php echo $this->pageTitle($this->translate('Revision browse'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<?php echo $this->scriptoBreadcrumbs(); ?>

<?php if ($revisions): ?>

<button class="compare-selected" data-url="<?php echo $this->escapeHtml($this->url(null, [], true)); ?>">Compare selected</button>

<table class="scripto-revisions tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Compare'); ?></th>
            <th><?php echo $this->translate('Date'); ?></th>
            <th><?php echo $this->translate('User'); ?></th>
            <th><?php echo $this->translate('Size'); ?></th>
            <th><?php echo $this->translate('Comment'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php $latestId = $revisions[0]['revid']; ?>
    <?php foreach ($revisions as $index => $revision): ?>
    <?php $childRevision = isset($revisions[$index + 1]) ? $revisions[$index + 1] : null; ?>
        <tr>
            <td>
                <div class="current-previous">
                <?php echo sprintf(
                    '%s | %s',
                    $latestId !== $revision['revid']
                        ? $this->hyperlink($this->translate('cur'), $this->url('admin/scripto-revision-compare', ['action' => 'compare', 'from-revision-id' => $revision['revid'], 'to-revision-id' => $latestId], true))
                        : $this->translate('cur'),
                    $childRevision
                        ? $this->hyperlink($this->translate('prev'), $this->url('admin/scripto-revision-compare', ['action' => 'compare', 'from-revision-id' => $childRevision['revid'], 'to-revision-id' => $revision['revid']], true))
                        : $this->translate('prev')
                ); ?>
                </div>
                <div class="from-revision">
                    <?php if ($latestId !== $revision['revid']): ?>
                    <input type="radio" name="from-revision-id" value="<?php echo $revision['revid']; ?>">
                    <?php endif; ?>
                </div>
                <div class="to-revision">
                    <?php if ($childRevision): ?>
                    <?php $hide = 0 < $index ? ' style="display: none;"' : ''; ?>
                    <input type="radio" name="to-revision-id" value="<?php echo $revision['revid']; ?>"<?php echo $hide; ?>>
                    <?php endif; ?>
                </div>
            </td>
            <td>
                <?php $datetime = new \DateTime($revision['timestamp']); ?>
                <?php echo $this->hyperlink(
                    $datetime->format('G:i, j F Y'),
                    $this->url('admin/scripto-revision-id', ['action' => 'show', 'revision-id' => $revision['revid']], true)
                ); ?>
            </td>
            <td><?php echo $this->escapeHtml($revision['user']); ?></td>
            <td><?php
            $sizeDiff = $childRevision ? $revision['size'] - $childRevision['size'] : $revision['size'];
            echo sprintf(
                '%s bytes (%s)',
                number_format($revision['size']),
                sprintf('%s%s', 0 < $sizeDiff ? '+' : '', number_format($sizeDiff))
            );
            ?></td>
            <td><i><?php echo $revision['parsedcomment']; ?></i></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
// Hide and show checkboxes to prevent reverse comparisons (i.e. where
// from-revision-id is greater than to-revision-id).
$(document).ready(function() {
    $('input[name="from-revision-id"]').first().prop('checked', true).change();
    $('input[name="to-revision-id"]').first().prop('checked', true).change();
});
$('input[name="from-revision-id"]').on('change', function() {
    var thisTr = $(this).closest('tr');
    thisTr.find('input[name="to-revision-id"]').hide();
    thisTr.prevAll().find('input[name="to-revision-id"]').show();
    thisTr.nextAll().find('input[name="to-revision-id"]').hide();
});
$('input[name="to-revision-id"]').on('change', function() {
    var thisTr = $(this).closest('tr');
    thisTr.find('input[name="from-revision-id"]').hide();
    thisTr.prevAll().find('input[name="from-revision-id"]').hide();
    thisTr.nextAll().find('input[name="from-revision-id"]').show();
});
$('button.compare-selected').on('click', function(e) {
    var fromId = $('input[name="from-revision-id"]:checked').val();
    var toId = $('input[name="to-revision-id"]:checked').val();
    window.location.href = $(this).data('url') + '/' + fromId + '/' + toId;
});
</script>

<?php else: ?>
<div class="no-resources">
    <p><?php echo $this->translate('This Scripto media has no revisions.'); ?></p>
</div>
<?php endif; ?>
