<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'show'); 
?>

<?php echo $this->pageTitle($this->translate('Revision compare'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Projects'), $this->url('admin/scripto-project')); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review project'), $this->url('admin/scripto-project-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review item'), $this->url('admin/scripto-item-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review media'), $this->url('admin/scripto-media-id', ['action' => 'review'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('View media revisions'), $this->url('admin/scripto-media-id', ['action' => 'revision'], true)); ?>
    <div class="separator"></div>
    <span class="current"><?php echo $this->translate('Revision compare'); ?></span>
</div>

<table>
    <tr>
        <td colspan="2"><?php
        $datetime = new \DateTime($fromRevision['timestamp']);
        echo sprintf(
            $this->translate('Revision as of %s by %s'),
            $datetime->format('G:i:s, j F Y'),
            $fromRevision['user']
        );
        echo sprintf('<br><i>%s</i><br>', $fromRevision['parsedcomment']);
        echo $fromRevision['parentid']
            ? $this->hyperlink($this->translate('Older revision'), $this->url(null, ['from-revision-id' => $fromRevision['parentid'], 'to-revision-id' => $fromRevision['revid']], true))
            : $this->translate('Older revision');
        ?></td>
        <td colspan="2"><?php
        $datetime = new \DateTime($toRevision['timestamp']);
        echo sprintf(
            $this->translate('Revision as of %s by %s'),
            $datetime->format('G:i:s, j F Y'),
            $toRevision['user']
        );
        echo sprintf('<br><i>%s</i><br>', $toRevision['parsedcomment']);
        echo $toRevision['childid']
            ? $this->hyperlink($this->translate('Newer revision'), $this->url(null, ['from-revision-id' => $toRevision['revid'], 'to-revision-id' => $toRevision['childid']], true))
            : $this->translate('Newer revision');
        ?></td>
    </tr>
    <?php if ($compare): ?>
    <?php echo $compare; ?>
    <?php else: ?>
    <tr><td colspan="4"><?php echo $this->translate('(No difference)'); ?></td></tr>
    <?php endif; ?>
</table>
