<?php $this->htmlElement('body')->appendAttribute('class', 'show'); ?>

<?php echo $this->pageTitle($this->translate('Revision revert'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'show'], true), ['class' => 'button']); ?>
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<?php echo $this->formElement($form->get('revertrevisionform_csrf')); ?>
<?php echo $this->form()->closeTag(); ?>

<p class="error"><?php echo $this->translate('Warning: You are reverting to an out-of-date revision. Any changes made since this revision will be lost.'); ?></p>

<textarea disabled><?php echo $revision['content']; ?></textarea>

<table>
    <tr>
        <td colspan="2"><?php echo $this->translate('Latest revision'); ?></td>
        <td colspan="2"><?php
        $datetime = new \DateTime($revision['timestamp']);
        echo sprintf(
            $this->translate('Reverting to revision %s by %s'),
            $this->hyperlink($datetime->format('G:i:s, j F Y'), $this->url(null, ['action' => 'show'], true)),
            $revision['user']
        );
        ?></td>
    </tr>
    <?php if ($compare): ?>
    <?php echo $compare; ?>
    <?php else: ?>
    <tr><td colspan="4"><?php echo $this->translate('(No difference)'); ?></td></tr>
    <?php endif; ?>
</table>
