<?php 
$this->headScript()->appendFile($this->assetUrl('js/scripto.css', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'show'); 
?>

<?php echo $this->pageTitle($this->translate('Revert revision'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Projects'), $this->url('admin/scripto-project')); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review project'), $this->url('admin/scripto-project-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review item'), $this->url('admin/scripto-item-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review media'), $this->url('admin/scripto-media-id', ['action' => 'review'], true)); ?>
    <div class="separator"></div>
    <span class="current"><?php echo $this->translate('View media revisions'); ?></span>
</div>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'show'], true), ['class' => 'button']); ?>
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<?php echo $this->formElement($form->get('revertrevisionform_csrf')); ?>
<?php echo $this->form()->closeTag(); ?>

<p class="error"><?php echo $this->translate('Warning: You are reverting to an out-of-date revision. Any changes made since this revision will be lost.'); ?></p>

<textarea disabled><?php echo $revision['content']; ?></textarea>

<table>
    <tr>
        <td colspan="2"><?php echo $this->translate('Latest revision'); ?></td>
        <td colspan="2"><?php
        $datetime = new \DateTime($revision['timestamp']);
        echo sprintf(
            $this->translate('Reverting to revision %s by %s'),
            $this->hyperlink($datetime->format('G:i:s, j F Y'), $this->url(null, ['action' => 'show'], true)),
            $revision['user']
        );
        ?></td>
    </tr>
    <?php if ($compare): ?>
    <?php echo $compare; ?>
    <?php else: ?>
    <tr><td colspan="4"><?php echo $this->translate('(No difference)'); ?></td></tr>
    <?php endif; ?>
</table>
