<?php $this->htmlElement('body')->appendAttribute('class', 'show'); ?>

<?php echo $this->pageTitle($this->translate('Revision'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div id="page-actions">
    <?php if ($revision['latestid'] !== $revision['revid']): ?>
    <?php echo $this->hyperlink($this->translate('Revert to this revision'), $this->url('admin/scripto-revision-id', ['action' => 'revert', 'revision-id' => $revision['revid']], true), ['class' => 'button']); ?>
    <?php endif; ?>
    <?php echo $this->hyperlink($this->translate('View revisions'), $this->url('admin/scripto-revision', ['action' => 'browse'], true), ['class' => 'button']); ?>
</div>

<p><?php
$datetime = new \DateTime($revision['timestamp']);
echo sprintf(
    $this->translate('Revision as of %s by %s'),
    $datetime->format('G:i:s, j F Y'),
    $revision['user']
);
?>
<br><i><?php echo $revision['parsedcomment']; ?></i><br>
<?php echo sprintf(
    '%s | %s | %s',
    $revision['parentid']
        ? $this->hyperlink($this->translate('Older revision'), $this->url(null, ['revision-id' => $revision['parentid']], true))
        : $this->translate('Older revision'),
    $revision['childid']
        ? $this->hyperlink($this->translate('Newer revision'), $this->url(null, ['revision-id' => $revision['childid']], true))
        : $this->translate('Newer revision'),
    $revision['latestid'] && $revision['latestid'] !== $revision['revid']
        ? $this->hyperlink($this->translate('Latest revision'), $this->url(null, ['revision-id' => $revision['latestid']], true))
        : $this->translate('Latest revision')
); ?></p>

<?php echo $revisionHtml; ?>
