<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.css', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'show'); 
?>

<?php echo $this->pageTitle($this->translate('Revision'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Projects'), $this->url('admin/scripto-project')); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review project'), $this->url('admin/scripto-project-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review item'), $this->url('admin/scripto-item-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review media'), $this->url('admin/scripto-media-id', ['action' => 'review'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('View media revisions'), $this->url('admin/scripto-media-id', ['action' => 'revision'], true)); ?>
    <div class="separator"></div>
    <span class="current"><?php echo $this->translate('View media revision'); ?></span>
</div>

<p><?php
$datetime = new \DateTime($revision['timestamp']);
echo sprintf(
    $this->translate('Revision as of %s by %s'),
    $datetime->format('G:i:s, j F Y'),
    $revision['user']
);
?>
<br><i><?php echo $revision['parsedcomment']; ?></i><br>
<?php echo sprintf(
    '%s | %s | %s | %s',
    $revision['parentid']
        ? $this->hyperlink($this->translate('View older'), $this->url(null, ['revision-id' => $revision['parentid']], true))
        : $this->translate('View older'),
    $revision['childid']
        ? $this->hyperlink($this->translate('View newer'), $this->url(null, ['revision-id' => $revision['childid']], true))
        : $this->translate('View newer'),
    $revision['latestid'] && $revision['latestid'] !== $revision['revid']
        ? $this->hyperlink($this->translate('View latest'), $this->url(null, ['revision-id' => $revision['latestid']], true))
        : $this->translate('View latest'),
    $revision['latestid'] !== $revision['revid']
        ? '<a href="#" class="sidebar-content" data-sidebar-selector="#revert-revision">' . $this->translate('Revert') . '</a>'
        : $this->translate('Revert')
); ?></p>

<?php echo $revisionHtml; ?>

<div id="revert-revision" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Revert revision'); ?></h3>
    <p class="error"><?php echo $this->translate('Warning: You are reverting to an out-of-date revision. Any changes made since this revision will be lost.'); ?></p>
    <?php echo $this->form()->openTag($form); ?>
    <button><?php echo $this->translate('Confirm reversion'); ?></button>
    <?php echo $this->formElement($form->get('revertrevisionform_csrf')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
