<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'show'); 
?>

<?php echo $this->pageTitle($this->translate('Revision'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <a href="#" class="expand button" aria-label="<?php echo $this->translate('Expand'); ?>"><?php echo $this->translate('Actions'); ?></a>
        <ul class="collapsible">
        <?php echo sprintf(
            '<li>%s</li><li>%s</li><li>%s</li><li>%s</li>',
            $revision['parentid']
                ? $this->hyperlink($this->translate('View older'), $this->url(null, ['revision-id' => $revision['parentid']], true))
                : '<span class="inactive">' . $this->translate('View older') . '</span>',
            $revision['childid']
                ? $this->hyperlink($this->translate('View newer'), $this->url(null, ['revision-id' => $revision['childid']], true))
                : '<span class="inactive">' . $this->translate('View newer') . '</span>',
            $revision['latestid'] && $revision['latestid'] !== $revision['revid']
                ? $this->hyperlink($this->translate('View latest'), $this->url(null, ['revision-id' => $revision['latestid']], true))
                : '<span class="inactive">' . $this->translate('View latest') . '</span>',
            $revision['latestid'] !== $revision['revid']
                ? '<a href="#" class="sidebar-content" data-sidebar-selector="#revert-revision">' . $this->translate('Revert') . '</a>'
                : '<span class="inactive">' . $this->translate('Revert') . '</span>'
        ); ?>
        </ul>
    </div>
</div>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Projects'), $this->url('admin/scripto-project')); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review project'), $this->url('admin/scripto-project-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review item'), $this->url('admin/scripto-item-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review media'), $this->url('admin/scripto-media-id', ['action' => 'review'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('View media revisions'), $this->url('admin/scripto-media-id', ['action' => 'revision'], true)); ?>
    <div class="separator"></div>
    <span class="current"><?php echo $this->translate('View media revision'); ?></span>
</div>

<h3>
<?php
$datetime = new \DateTime($revision['timestamp']);
echo sprintf(
    $this->translate('Revision as of %s by %s'),
    $datetime->format('G:i:s, j F Y'),
    $revision['user']
);
?>
</h3>

<?php echo $this->sectionNav([
    'revision-html' => $this->translate('HTML'),
    'revision-diff' => $this->translate('Compare'),
]); ?>

<div id="revision-html" class="active section">
    <?php $parsedComment = $revision['parsedcomment']; ?>
    <?php if ($parsedComment !== ''):?>
    <p class="parsed-comment"><?php echo $revision['parsedcomment']; ?></p>
    <?php endif; ?>
    
    <?php echo $revisionHtml; ?>
</div>

<div id="revision-diff" class="section">
    <table>
        <tr>
            <td colspan="2"><?php echo $this->translate('Latest revision'); ?></td>
            <td colspan="2"><?php
            $datetime = new \DateTime($revision['timestamp']);
            echo sprintf(
                $this->translate('Reverting to revision %s by %s'),
                $this->hyperlink($datetime->format('G:i:s, j F Y'), $this->url(null, ['action' => 'show'], true)),
                $revision['user']
            );
            ?></td>
        </tr>
        <?php if ($compare): ?>
        <?php echo $compare; ?>
        <?php else: ?>
        <tr><td colspan="4"><?php echo $this->translate('(No difference)'); ?></td></tr>
        <?php endif; ?>
    </table>
</div>

<div id="revert-revision" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Revert revision'); ?></h3>
    <p class="error"><?php echo $this->translate('Warning: You are reverting to an out-of-date revision. Any changes made since this revision will be lost.'); ?></p>
    <?php echo $this->form()->openTag($form); ?>
    <button><?php echo $this->translate('Confirm reversion'); ?></button>
    <?php echo $this->formElement($form->get('revertrevisionform_csrf')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
