<?php
$this->scripto()->postTitle($item->displayTitle());
?>
<div class="resource-content">
    <?php if ($itemMetadata = $item->displayValues()): ?>
    <div class="resource-metadata">
        <?php echo $itemMetadata; ?>
    </div>
    <?php endif; ?>
    <div class="media resource-list">
        <div class="media list-head">
            <?php if ($sMedias): ?>
            <div class="list-layout">
                <span class="layout-label"><?php echo $this->translate('Layout'); ?></span>
                <button class="list" aria-label="<?php echo $this->escapeHtml($this->translate('List')); ?>"<?php echo 'list' === $project->browseLayout() ? ' disabled' : ''; ?>></button>
                <button class="grid" aria-label="<?php echo $this->escapeHtml($this->translate('Grid')); ?>"<?php echo 'list' !== $project->browseLayout() ? ' disabled' : ''; ?>></button>
            </div>
            <?php endif; ?>
            <div class="sorting-toggle">
                <a href="#" class="sorting-heading menu-toggle"><?php echo $this->translate('Sort'); ?></a>
                <?php echo $this->sortSelector([
                    [
                        'label' => $this->translate('Position'),
                        'value' => 'position'
                    ],
                    [
                        'label' => $this->translate('Last edited'),
                        'value' => 'edited'
                    ],
                    [
                        'label' => $this->translate('Last completed'),
                        'value' => 'completed'
                    ],
                    [
                        'label' => $this->translate('Last approved'),
                        'value' => 'approved'
                    ],
                ]); ?>
            </div>
            <div class="filtering-toggle">
                <a href="#" class="filtering-heading menu-toggle"><?php echo $this->translate('Filter'); ?></a>
                <?php echo $this->filterSelector([
                    [
                        'label' => $this->translate('Is edited'),
                        'value' => 'is_edited',
                    ],
                    [
                        'label' => $this->translate('Is not edited'),
                        'value' => 'is_not_edited',
                    ],
                    [
                        'label' => $this->translate('Is completed'),
                        'value' => 'is_completed',
                    ],
                    [
                        'label' => $this->translate('Is not completed'),
                        'value' => 'is_not_completed',
                    ],
                    [
                        'label' => $this->translate('Is approved'),
                        'value' => 'is_approved',
                    ],
                    [
                        'label' => $this->translate('Is not approved'),
                        'value' => 'is_not_approved',
                    ],
                ]); ?>
            </div>
            <div class="title-toggle">
                <label><input type="checkbox" name="title-toggle"><?php echo $this->translate('Show original titles'); ?></label>
            </div>
            <?php echo $this->pagination(); ?>
        </div>
        <?php if ($sMedias): ?>
        <table<?php echo 'list' !== $project->browseLayout() ? ' style="display: none"' : ''; ?> class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
            <thead>
                <tr>
                    <th class="title"><?php echo $this->scripto()->translate($project->mediaType(), 'Media'); ?></th>
                    <th class="last-edited"><?php echo $this->scripto()->translate($project->contentType(), 'Last edited'); ?></th>
                    <th class="status"><?php echo $this->translate('Status'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($sMedias as $sMedia): ?>
                <tr class="resource-row">
                    <td>
                        <div class="title-flex">
                            <?php echo $sMedia->linkRaw($this->thumbnail($sMedia, 'square', [
                                'title' => $this->scripto()->translate($project->mediaType(), 'Primary media'),
                                'alt' => $this->scripto()->translate($project->mediaType(), 'Primary media'),
                            ])); ?>
                            <div class="title-meta">
                                <span class="original-number"><?php echo $sMedia->linkRaw(sprintf('#%s', $sMedia->position())); ?></span>
                                <span class="original-title"><?php echo $sMedia->linkRaw($sMedia->media()->displayTitle()); ?></span>
                                <?php echo $sMedia->linkRaw($this->scripto()->translate($project->contentType(), 'Edit'), 'edit', [
                                    'class' => 'edit-link',
                                ]); ?>
                            </div>
                        </div>
                    </td>
                    <td class="percentage">
                        <span class="last-edited"><?php echo $sMedia->edited() ? $this->i18n()->dateFormat($sMedia->edited(), 'long', 'medium') : $this->scripto()->translate($project->contentType(), 'Not edited'); ?></span>
                    </td>
                    <td>
                        <span class="status"><?php echo $this->translate($sMedia->status()); ?></span>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="resource-grid"<?php echo 'list' === $project->browseLayout() ? ' style="display: none"' : ''; ?>>
            <?php foreach ($sMedias as $sMedia): ?>
            <div class="resource-tile">
                <?php echo $sMedia->linkRaw($this->thumbnail($sMedia, 'square', [
                    'title' => $this->scripto()->translate($project->mediaType(), 'Primary media'),
                    'alt' => $this->scripto()->translate($project->mediaType(), 'Primary media')
                ])); ?>
                <h4><span class="original-number"><?php echo $sMedia->linkRaw(sprintf('#%s', $sMedia->position())); ?></span>
                <span class="original-title"><?php echo $sMedia->linkRaw($sMedia->media()->displayTitle()); ?></span></h4>
                <?php echo $sMedia->linkRaw($this->scripto()->translate($project->contentType(), 'Edit'), 'edit', [
                    'class' => 'edit-link',
                ]); ?>
                <div class="last-edited"><span class="meta-label"><?php echo $this->scripto()->translate($project->contentType(), 'Last edited'); ?></span> <?php echo $sMedia->edited() ? $this->i18n()->dateFormat($sMedia->edited(), 'long', 'medium') : $this->scripto()->translate($project->contentType(), 'Not edited'); ?></div>
                <div class="status"><span class="meta-label"><?php echo $this->translate('Status'); ?></span> <?php echo $this->translate($sMedia->status()); ?></div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php else: ?>
        <div class="no-resources">
            <p><?php echo $this->scripto()->translate($project->mediaType(), 'No Scripto media found'); ?></p>
        </div>
        <?php endif; ?>
    </div>
</div>
