<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/featherlight/featherlight.min.css', 'Scripto'));
$this->headLink()->appendStylesheet('https://use.fontawesome.com/releases/v5.0.9/css/all.css');
$this->headScript()->appendFile($this->assetUrl('vendor/jquery-panzoom/jquery.panzoom.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('vendor/featherlight/featherlight.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/LmlEditor.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/common/media.js', 'Scripto'));

$this->scripto()->postTitle(sprintf($this->scripto()->translate($project->mediaType(), 'Notes for %s: %s #%s'), $sItem->link($item->displayTitle()), ucfirst($project->mediaType()), $sMedia->position()));
$this->scripto()->postSubtitle(sprintf($this->translate('Original title: %s'), $sMedia->link($media->displayTitle())));
?>
<?php echo $this->form()->openTag($mediaForm); ?>
<?php echo $this->formElement($mediaForm->get('mediapublicappform_csrf')); ?>
    <div class="media-head">
        <?php echo $this->scripto()->watchlistToggle($sMedia, true); ?>
        <input type="submit" class="save" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>">
        <?php echo $sMedia->link($this->translate('Cancel'), 'talk', ['class' => 'button']); ?>
    </div>
    <div id="wikitext" class="resource-content">
        <div id="media-column">
            <div class="media render">
                <?php if ($sMedia->isRenderableImage()): ?>
                <div class="panzoom-container image">
                    <div class="zoom-controls">
                        <button class="zoom-in" aria-label="<?php echo $this->escapeHtml($this->translate('Zoom in')); ?>" title="<?php echo $this->escapeHtml($this->translate('Zoom in')); ?>"></button>
                        <button class="zoom-out" aria-label="<?php echo $this->escapeHtml($this->translate('Zoom out')); ?>" title="<?php echo $this->escapeHtml($this->translate('Zoom out')); ?>"></button>
                        <button class="rotate-right" aria-label="<?php echo $this->escapeHtml($this->translate('Rotate right')); ?>" title="<?php echo $this->escapeHtml($this->translate('Rotate right')); ?>"></button>
                        <button class="rotate-left" aria-label="<?php echo $this->escapeHtml($this->translate('Rotate left')); ?>" title="<?php echo $this->escapeHtml($this->translate('Rotate left')); ?>"></button>
                        <button class="reset"><?php echo $this->translate('Reset'); ?></button>
                    </div>
                    <div class="media-render">
                        <img src="<?php echo $this->escapeHtml($media->originalUrl()); ?>">
                    </div>
                </div>
                <?php else: ?>
                <div class="panzoom-container">
                    <?php echo $media->render(['link' => null]); ?>
                </div>
                <?php endif; ?>
            </div>
            <div class="media copy">
                <h3><?php echo $this->scripto()->translate($project->contentType(), 'HTML'); ?></h3>
                <?php $pageHtml = $sMedia->pageHtml(0); ?>
                <?php echo $pageHtml  ? $pageHtml : sprintf('<span>[%s]</span>', $this->scripto()->translate($project->contentType(), 'No HTML')); ?>
            </div>
            <?php $displayValues = $media->displayValues(); ?>
            <?php if ($displayValues): ?>
            <div class="media metadata">
                <h3><?php echo $this->translate('Metadata'); ?></h3>
                <?php echo $displayValues; ?>
            </div>
            <?php endif; ?>
        </div>
        <div class="wikitext-flex notes-column">
            <p><?php echo sprintf($this->translate('Notes are a workspace where project participants can keep ideas and observations regarding the %s of the %s. When contributing to the notes, it is encouraged to include the user and timestamp.'), $project->contentType(), $project->mediaType()); ?></p>
            <div class="change-summary">
                <?php echo $this->formText($mediaForm->get('summary')); ?>
            </div>
            <div class="textarea-flex">
                <div class="wikitext-editor-buttons" data-signature="<?php echo $this->escapeHtml($this->scripto()->getUserSignature()); ?>" data-lml-editor-translations="<?php echo $this->escapeHtml($this->scripto()->getLmlEditorTranslations()); ?>"></div>
                <?php echo $this->formTextarea($mediaForm->get('wikitext')); ?>
            </div>
        </div>
    </div>
</form>
<script>
// Add wikitext editor buttons to the wikitext textarea.
Scripto.enableMediaTalkEditor(
    document.getElementsByClassName('wikitext-editor-text'),
    document.getElementsByClassName('wikitext-editor-buttons')
);
</script>
