<?php
$this->headLink()->appendStylesheet('https://use.fontawesome.com/releases/v5.0.9/css/all.css');
$this->headScript()->appendFile($this->assetUrl('js/common/media.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/LmlEditor.js', 'Scripto'));

$this->scripto()->postTitle(sprintf($this->scripto()->translate($project->mediaType(), '%s: Media #%s'), $sItem->link($item->displayTitle()), $sMedia->position()));
$this->scripto()->postSubtitle(sprintf($this->translate('Original title: %s'), $media->displayTitle()));
?>
<?php echo $this->form()->openTag($mediaForm); ?>
<?php echo $this->formElement($mediaForm->get('mediapublicappform_csrf')); ?>
    <div class="media-head">
        <?php echo $this->scripto()->watchlistToggle($sMedia); ?>
        <div class="protection-field">
            <?php $editAccess = $sMedia->editAccess(0); ?>
            <div class="current-protection"><strong><?php echo $this->translate('Protection: '); ?></strong><?php echo $this->translate($editAccess['label']); ?></div>
            <div class="protection-expiration"><strong><?php echo $this->translate('Expiration: '); ?></strong><?php echo $editAccess['expiry'] ? $this->i18n()->dateFormat($editAccess['expiry'], 'short', 'short') : $this->translate('Never'); ?></div>
        </div>
        <div class="status-field">
            <div class="current-status"><strong><?php echo $this->translate('Status: '); ?></strong><?php echo $this->translate($sMedia->status()); ?></div>
            <label for="mark_complete"><?php echo $this->translate('Mark this revision as complete'); ?></label>
            <?php echo $this->formCheckbox($mediaForm->get('mark_complete')); ?>
        </div>
        <input type="submit" class="save" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>">
        <?php echo $sMedia->link($this->translate('Cancel'), 'show', ['class' => 'button']); ?>
    </div>
    <div id="wikitext" class="resource-content">
        <div id="wikitext-layout" class="horizontal">
            <h3><?php echo sprintf($this->scripto()->translate($project->mediaType(), '%s: Media #%s'), $item->displayTitle(), $sMedia->position()); ?></h3>
            <button type="button" id="fullscreen"><span class="go-fullscreen"><?php echo $this->translate('Go full screen'); ?></span><span class="exit-fullscreen"><?php echo $this->translate('Exit full screen'); ?></span></button>
            <div class="layout">
                <label><?php echo $this->translate('Layout'); ?></label>
                <button type="button" name="horizontal" id="horizontal-layout" class="active" aria-label="<?php echo $this->escapeHtml($this->translate('Horizontal view')); ?>" title="<?php echo $this->escapeHtml($this->translate('Horizontal view')); ?>" disabled=""></button>
                <button type="button" name="vertical" id="vertical-layout" aria-label="<?php echo $this->escapeHtml($this->translate('Vertical view')); ?>" title="<?php echo $this->escapeHtml($this->translate('Vertical view')); ?>"></button>
            </div>
            <div class="wikitext-flex">
                <?php if ($sMedia->isRenderableImage()): ?>
                <?php echo $this->partial('common/media-viewer'); ?>
                <?php else: ?>
                <div class="panzoom-container">
                    <?php echo $media->render(['link' => null]); ?>
                </div>
                <?php endif; ?>
                <div class="textarea-flex">
                    <div class="change-summary">
                        <?php echo $this->formText($mediaForm->get('summary')); ?>
                    </div>
                    <div class="wikitext-editor-buttons" data-lml-editor-translations="<?php echo $this->escapeHtml($this->scripto()->getLmlEditorTranslations()); ?>"></div>
                    <?php echo $this->formTextarea($mediaForm->get('wikitext')); ?>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
// Add wikitext editor buttons to the wikitext textarea.
Scripto.enableMediaEditor(
    document.getElementsByClassName('wikitext-editor-text'),
    document.getElementsByClassName('wikitext-editor-buttons')
);
</script>
