<?php
$this->headScript()->appendFile($this->assetUrl('vendor/panzoom-4.3.1/dist/panzoom.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/media-viewer.js', 'Scripto'));
?>
<div id="media-viewer">
    <div id="panzoom-buttons">
        <button id="panzoom-zoom-in" aria-label="<?php echo $this->translate('Zoom in'); ?>" title="<?php echo $this->translate('Zoom in'); ?>"></button>
        <button id="panzoom-zoom-out" aria-label="<?php echo $this->translate('Zoom out'); ?>" title="<?php echo $this->translate('Zoom out'); ?>"></button>
        <button id="panzoom-rotate-left" aria-label="<?php echo $this->translate('Rotate left'); ?>" title="<?php echo $this->translate('Rotate left'); ?>"></button>
        <button id="panzoom-rotate-right" aria-label="<?php echo $this->translate('Rotate right'); ?>" title="<?php echo $this->translate('Rotate right'); ?>"></button>
        <button id="panzoom-reset" ><?php echo $this->translate('Reset'); ?></button>
    </div>
    <div id="panzoom-container" tabindex="0">
        <div id="panzoom">
            <img id="panzoom-img" src="<?php echo $this->escapeHtml($media->originalUrl()); ?>">
        </div>
    </div>
</div>
