<?php
$this->headLink()->appendStylesheet('https://use.fontawesome.com/releases/v5.0.9/css/all.css');
$this->headScript()->appendFile($this->assetUrl('js/LmlEditor.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/common/media.js', 'Scripto'));

$this->scripto()->postTitle(sprintf($this->scripto()->translate($project->mediaType(), 'Notes for %s: %s #%s'), $sItem->link($item->displayTitle()), ucfirst($project->mediaType()), $sMedia->position()));
$this->scripto()->postSubtitle(sprintf($this->translate('Original title: %s'), $sMedia->link($media->displayTitle())));
?>

<?php echo $this->partial('common/media-head.phtml'); ?>
<div class="resource-content">
    <div id="media-column">
        <div class="media render">
            <?php if ($sMedia->isRenderableImage()): ?>
            <?php echo $this->partial('common/media-viewer'); ?>
            <?php else: ?>
            <div class="panzoom-container">
                <?php echo $media->render(['link' => null]); ?>
            </div>
            <?php endif; ?>
        </div>
        <div class="media copy">
            <h3><?php echo $this->scripto()->translate($project->contentType(), 'HTML'); ?></h3>
            <?php $pageHtml = $sMedia->pageHtml(0); ?>
            <?php echo $pageHtml  ? $pageHtml : sprintf('<span>[%s]</span>', $this->scripto()->translate($project->contentType(), 'No HTML')); ?>
        </div>
        <?php $displayValues = $media->displayValues(); ?>
        <?php if ($displayValues): ?>
        <div class="media metadata">
            <h3><?php echo $this->translate('Metadata'); ?></h3>
            <?php echo $displayValues; ?>
        </div>
        <?php endif; ?>
    </div>
    <div class="notes-column">
        <?php $pageHtml = $sMedia->pageHtml(1); ?>
        <?php echo $pageHtml  ? $pageHtml : sprintf('<span>[%s]</span>', $this->translate('No notes yet.')); ?>
        <ul class="note-actions">
        <?php if ($userCanEdit): ?>
            <li><?php echo $sMedia->link($this->translate('Edit'), 'edit-talk'); ?></li>
            <li><?php echo $this->hyperlink($this->translate('Browse notes history'), $this->url('scripto-talk-revision', ['action' => 'browse-talk'], true)); ?></li>
        <?php endif; ?>
        </ul>
    </div>
</div>
