<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/featherlight/featherlight.min.css', 'Scripto'));
$this->headLink()->appendStylesheet('https://use.fontawesome.com/releases/v5.0.9/css/all.css');
$this->headScript()->appendFile($this->assetUrl('vendor/jquery-panzoom/jquery.panzoom.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('vendor/featherlight/featherlight.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/LmlEditor.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/common/media.js', 'Scripto'));

$this->scripto()->postTitle(sprintf($this->translate('Discussion: %s'), $media->displayTitle()));
$this->scripto()->postSubtitle(sprintf($this->translate('Part of %s'), $sItem->link($item->displayTitle())));
?>
<div class="media-head">
    <div class="media-tabs">
        <?php echo $sMedia->link($this->translate('Text'), 'show', ['class' => 'button']); ?>
        <span class="inactive tab button"><?php echo $this->translate('Discussion'); ?></span>
    </div>
    <div class="tab-actions">
    <?php if ($userCanEdit): ?>
        <?php echo $sMedia->link($this->translate('Discuss'), 'edit-talk'); ?>
        <?php echo $this->hyperlink($this->translate('View discussion history'), $this->url('scripto-talk-revision', ['action' => 'browse-talk'], true)); ?>
    <?php endif; ?>
    <?php echo $this->scripto()->watchlistToggle($sMedia); ?>
    </div>
    <?php echo $this->scripto()->mediaPagination('talk'); ?>
</div>
<div class="resource-content">
    <div class="media metadata">
        <h3><?php echo $this->translate('Metadata'); ?></h3>
        <?php $displayValues = $media->displayValues(); ?>
        <?php echo $displayValues  ? $displayValues : sprintf('<span>[%s]</span>', $this->translate('No metadata')); ?>
    </div>
    <div class="media html">
    <?php if ($sMedia->isRenderableImage()): ?>
    <h3><?php echo $this->translate('Media'); ?></h3>
    <div class="panzoom-container image">
        <div class="zoom-controls">
            <button class="zoom-in" aria-label="<?php echo $this->escapeHtml($this->translate('Zoom in')); ?>" title="<?php echo $this->escapeHtml($this->translate('Zoom in')); ?>"></button>
            <button class="zoom-out" aria-label="<?php echo $this->escapeHtml($this->translate('Zoom out')); ?>" title="<?php echo $this->escapeHtml($this->translate('Zoom out')); ?>"></button>
            <button class="rotate-right" aria-label="<?php echo $this->escapeHtml($this->translate('Rotate right')); ?>" title="<?php echo $this->escapeHtml($this->translate('Rotate right')); ?>"></button>
            <button class="rotate-left" aria-label="<?php echo $this->escapeHtml($this->translate('Rotate left')); ?>" title="<?php echo $this->escapeHtml($this->translate('Rotate left')); ?>"></button>
            <button class="reset"><?php echo $this->translate('Reset'); ?></button>
        </div>
        <div class="media-render">
            <img src="<?php echo $this->escapeHtml($media->originalUrl()); ?>">
        </div>
    </div>
    <?php else: ?>
    <div class="panzoom-container">
        <?php echo $media->render(['link' => null]); ?>
    </div>
    <?php endif; ?>
        <h3><?php echo $this->translate('Discussion'); ?></h3>
        <?php $pageHtml = $sMedia->pageHtml(1); ?>
        <?php echo $pageHtml  ? $pageHtml : sprintf('<span>[%s]</span>', $this->translate('No discussion yet.')); ?>
    </div>
</div>
