<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/featherlight/featherlight.min.css', 'Scripto'));
$this->headLink()->appendStylesheet('https://use.fontawesome.com/releases/v5.0.9/css/all.css');
$this->headScript()->appendFile($this->assetUrl('vendor/jquery-panzoom/jquery.panzoom.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('vendor/featherlight/featherlight.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/LmlEditor.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/common/media.js', 'Scripto'));
$this->scripto()->postTitle(sprintf($this->scripto()->translate($project->mediaType(), '%s: %s #%s'), $sItem->link($item->displayTitle()), ucfirst($project->mediaType()), $sMedia->position()));
$this->scripto()->postSubtitle(sprintf($this->translate('Original title: %s'), $sMedia->link($media->displayTitle())));
?>
<?php echo $this->partial('common/media-head.phtml'); ?>
<div class="resource-content">
    <div class="media render">
    <?php if ($sMedia->isRenderableImage()): ?>
    <div class="panzoom-container image">
        <div class="zoom-controls">
            <button class="zoom-in" aria-label="<?php echo $this->escapeHtml($this->translate('Zoom in')); ?>" title="<?php echo $this->escapeHtml($this->translate('Zoom in')); ?>"></button>
            <button class="zoom-out" aria-label="<?php echo $this->escapeHtml($this->translate('Zoom out')); ?>" title="<?php echo $this->escapeHtml($this->translate('Zoom out')); ?>"></button>
            <button class="rotate-right" aria-label="<?php echo $this->escapeHtml($this->translate('Rotate right')); ?>" title="<?php echo $this->escapeHtml($this->translate('Rotate right')); ?>"></button>
            <button class="rotate-left" aria-label="<?php echo $this->escapeHtml($this->translate('Rotate left')); ?>" title="<?php echo $this->escapeHtml($this->translate('Rotate left')); ?>"></button>
            <button class="reset"><?php echo $this->translate('Reset'); ?></button>
        </div>
        <div class="media-render">
            <img src="<?php echo $this->escapeHtml($media->originalUrl()); ?>">
        </div>
    </div>
    <?php else: ?>
    <div class="panzoom-container">
        <?php echo $media->render(['link' => null]); ?>
    </div>
    <?php endif; ?>
    </div>
    <div class="media html">
        <div class="copy">
            <h3><?php echo $this->scripto()->translate($project->contentType(), 'HTML'); ?></h3>
            <?php $pageHtml = $sMedia->pageHtml(0); ?>
            <?php echo $pageHtml  ? $pageHtml : sprintf('<span>[%s]</span>', $this->scripto()->translate($project->contentType(), 'No HTML')); ?>
        </div>
        <?php $displayValues = $media->displayValues(); ?>
        <?php if ($displayValues): ?>
        <div class="media metadata">
            <h3><?php echo $this->translate('Metadata'); ?></h3>
            <?php echo $displayValues; ?>
        </div>
        <?php endif; ?>
    </div>
</div>
