<?php
$this->scripto()->postTitle(sprintf($this->translate('Discussion revisions: %s'), $media->displayTitle()));
?>
<div class="resource-content">
    <div class="revisions resource-list">
        <div class="browse-controls">
            <button class="compare-selected" data-url="<?php echo $this->escapeHtml($this->url(null, [], true)); ?>">Compare selected</button>
            <?php echo $this->scripto()->mediawikiPagination(); ?>
        </div>
        <table>
            <thead>
                <tr>
                    <th><?php echo $this->translate('Compare'); ?></th>
                    <th><?php echo $this->translate('Date'); ?></th>
                    <th><?php echo $this->translate('User'); ?></th>
                    <th><?php echo $this->translate('Size'); ?></th>
                    <th class="comment"><?php echo $this->translate('Comment'); ?></th>
                </tr>
            </thead>
            <tbody>
            <?php $latestId = $revisions[0]['revid']; ?>
            <?php foreach ($revisions as $index => $revision): ?>
            <?php $childRevision = isset($revisions[$index + 1]) ? $revisions[$index + 1] : null; ?>
                <tr>
                    <td>
                        <div class="compare-controls">
                            <div class="current-previous">
                            <?php echo sprintf(
                                '%s | %s',
                                $latestId !== $revision['revid']
                                    ? $this->hyperlink($this->translate('cur'), $this->url('scripto-talk-revision-compare', ['action' => 'compare-talk', 'from-revision-id' => $revision['revid'], 'to-revision-id' => $latestId], true))
                                    : $this->translate('cur'),
                                $childRevision
                                    ? $this->hyperlink($this->translate('prev'), $this->url('scripto-talk-revision-compare', ['action' => 'compare-talk', 'from-revision-id' => $childRevision['revid'], 'to-revision-id' => $revision['revid']], true))
                                    : $this->translate('prev')
                            ); ?>
                            </div>
                            <div class="from-revision">
                                <?php if ($latestId !== $revision['revid']): ?>
                                <input type="radio" name="from-revision-id" aria-label="<?php echo $this->translate('From revision'); ?>" value="<?php echo $revision['revid']; ?>">
                                <?php endif; ?>
                            </div>
                            <div class="to-revision">
                                <?php if ($childRevision): ?>
                                <?php $hide = 0 < $index ? ' style="display: none;"' : ''; ?>
                                <input type="radio" name="to-revision-id" aria-label="<?php echo $this->translate('To revision'); ?>" value="<?php echo $revision['revid']; ?>"<?php echo $hide; ?>>
                                <?php endif; ?>
                            </div>
                        </div>
                    </td>
                    <td>
                        <?php echo $this->hyperlink(
                            $revision['timestamp']->format('G:i:s, j F Y'),
                            $this->url('scripto-talk-revision-id', ['action' => 'show-talk', 'revision-id' => $revision['revid']], true)
                        ); ?>
                        <?php if ($revision['revid'] === $sMedia->completedRevision()): ?>
                        <div class="green">This revision marked as completed.</div>
                        <?php endif; ?>
                        <?php if ($revision['revid'] === $sMedia->approvedRevision()): ?>
                        <div class="green">This revision marked as approved.</div>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $this->hyperlink($revision['user'], $this->url('scripto-user-contributions', ['user-id' => $revision['user']])); ?></td>
                    <td><?php
                    $sizeDiff = $childRevision ? $revision['size'] - $childRevision['size'] : 0;
                    echo sprintf(
                        '%s bytes (%s)',
                        number_format($revision['size']),
                        sprintf('%s%s', 0 < $sizeDiff ? '+' : '', number_format($sizeDiff))
                    );
                    ?></td>
                    <td><i><?php echo strip_tags($revision['parsedcomment']); ?></i></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script>
// Hide and show checkboxes to prevent reverse comparisons (i.e. where
// from-revision-id is greater than to-revision-id).
$(document).ready(function() {
    $('input[name="from-revision-id"]').first().prop('checked', true).change();
    $('input[name="to-revision-id"]').first().prop('checked', true).change();
});
$('input[name="from-revision-id"]').on('change', function() {
    var thisTr = $(this).closest('tr');
    thisTr.find('input[name="to-revision-id"]').hide();
    thisTr.prevAll().find('input[name="to-revision-id"]').show();
    thisTr.nextAll().find('input[name="to-revision-id"]').hide();
});
$('input[name="to-revision-id"]').on('change', function() {
    var thisTr = $(this).closest('tr');
    thisTr.find('input[name="from-revision-id"]').hide();
    thisTr.prevAll().find('input[name="from-revision-id"]').hide();
    thisTr.nextAll().find('input[name="from-revision-id"]').show();
});
$('button.compare-selected').on('click', function(e) {
    var fromId = $('input[name="from-revision-id"]:checked').val();
    var toId = $('input[name="to-revision-id"]:checked').val();
    window.location.href = $(this).data('url') + '/' + fromId + '/' + toId;
});
</script>
