<?php
$this->headScript()->appendFile($this->assetUrl('js/common/revision-browse.js', 'Scripto'));
$this->scripto()->postTitle(sprintf($this->scripto()->translate($project->mediaType(), 'Notes history for %s: Media #%s'), $sItem->link($item->displayTitle()), $sMedia->position()));
$this->scripto()->postSubtitle($sMedia->link($media->displayTitle(), 'show-talk'));
?>
<div class="resource-content">
    <div class="revisions resource-list">
        <?php echo $this->partial('common/media-head.phtml'); ?>
        <?php if ($revisions): ?>
        <div class="browse-controls">
            <button class="compare-selected" data-url="<?php echo $this->escapeHtml($this->url(null, [], true)); ?>"><?php echo $this->translate('Compare selected'); ?></button>
            <?php echo $sMedia->link($this->translate('Back to notes'), 'talk', ['class' => 'back-to-notes']); ?>
            <?php echo $this->scripto()->mediawikiPagination(); ?>
        </div>
        <table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
            <thead>
                <tr>
                    <th><?php echo $this->translate('Compare'); ?></th>
                    <th><?php echo $this->translate('Date'); ?></th>
                    <th><?php echo $this->translate('User'); ?></th>
                    <th><?php echo $this->translate('Size'); ?></th>
                    <th class="comment"><?php echo $this->translate('Comment'); ?></th>
                </tr>
            </thead>
            <tbody>
            <?php $latestId = $revisions[0]['revid']; ?>
            <?php foreach ($revisions as $index => $revision): ?>
            <?php $childRevision = isset($revisions[$index + 1]) ? $revisions[$index + 1] : null; ?>
                <tr>
                    <td>
                        <div class="compare-controls">
                            <div class="current-previous">
                            <?php echo sprintf(
                                '%s | %s',
                                $latestId !== $revision['revid']
                                    ? $this->hyperlink($this->translate('cur'), $this->url('scripto-talk-revision-compare', ['action' => 'compare-talk', 'from-revision-id' => $revision['revid'], 'to-revision-id' => $latestId], true))
                                    : $this->translate('cur'),
                                $childRevision
                                    ? $this->hyperlink($this->translate('prev'), $this->url('scripto-talk-revision-compare', ['action' => 'compare-talk', 'from-revision-id' => $childRevision['revid'], 'to-revision-id' => $revision['revid']], true))
                                    : $this->translate('prev')
                            ); ?>
                            </div>
                            <div class="from-revision">
                                <?php if ($latestId !== $revision['revid']): ?>
                                <input type="radio" name="from-revision-id" aria-label="<?php echo $this->translate('From revision'); ?>" value="<?php echo $revision['revid']; ?>">
                                <?php endif; ?>
                            </div>
                            <div class="to-revision">
                                <?php if ($childRevision): ?>
                                <?php $hide = 0 < $index ? ' style="display: none;"' : ''; ?>
                                <input type="radio" name="to-revision-id" aria-label="<?php echo $this->translate('To revision'); ?>" value="<?php echo $revision['revid']; ?>"<?php echo $hide; ?>>
                                <?php endif; ?>
                            </div>
                        </div>
                    </td>
                    <td>
                        <?php echo $this->hyperlink(
                            $revision['timestamp']->format('G:i:s, j F Y'),
                            $this->url('scripto-talk-revision-id', ['action' => 'show-talk', 'revision-id' => $revision['revid']], true)
                        ); ?>
                        <?php if ($revision['revid'] === $sMedia->completedRevision()): ?>
                        <div class="green">This revision marked as completed.</div>
                        <?php endif; ?>
                        <?php if ($revision['revid'] === $sMedia->approvedRevision()): ?>
                        <div class="green">This revision marked as approved.</div>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $this->hyperlink($revision['user'], $this->url('scripto-user-contributions', ['action' => 'contributions', 'user-id' => $revision['user']], true)); ?></td>
                    <td><?php
                    $sizeDiff = $childRevision ? $revision['size'] - $childRevision['size'] : 0;
                    echo sprintf(
                        $this->translate('%s bytes (%s)'),
                        number_format($revision['size']),
                        sprintf('%s%s', 0 < $sizeDiff ? '+' : '', number_format($sizeDiff))
                    );
                    ?></td>
                    <td><i><?php echo strip_tags($revision['parsedcomment']); ?></i></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php else: ?>
        <div class="no-resources">
            <p><?php echo $this->translate('No revisions found'); ?></p>
        </div>
        <?php endif; ?>
    </div>
</div>
