<?php
$this->scripto()->postTitle(sprintf($this->translate('Compare revisions: %s'), $sMedia->link($this->escapeHtml($media->displayTitle()), 'show')));
?>
<div class="resource-content">
    <div class="browse-controls">
        <?php echo $this->hyperlink($this->translate('Return to revision history'), $this->url('scripto-revision', ['action' => 'browse'], true)); ?>
        <?php echo $this->scripto()->compareRevisionsPagination(); ?>
    </div>
    <table id="compare-table">
        <colgroup>
            <col class="diff-marker">
            <col class="diff-context">
            <col class="diff-marker">
            <col class="diff-context">
        </colgroup>
        <thead>
            <tr>
                <th colspan="2">
                    <div class="revision-timestamp"><?php echo $this->hyperlink(sprintf($this->translate('Revision as of %s'), $fromRevision['timestamp']->format('G:i:s, j F Y')), $this->url('scripto-revision-id', ['action' => 'show', 'revision-id' => $fromRevision['revid']], true)); ?>
                    <?php echo sprintf(
                        $this->translate('by %s'),
                        $this->hyperlink($fromRevision['user'], $this->url('scripto-user-contributions', ['action' => 'contributions', 'user-id' => $fromRevision['user']], true))
                    ); ?></div>
                    <?php if ($fromRevision['parsedcomment']): ?>
                    <div class="parsed-comment"><?php echo strip_tags($fromRevision['parsedcomment']); ?></div>
                    <?php endif; ?>
                </th>
                <th colspan="2">
                    <div class="revision-timestamp"><?php echo $this->hyperlink(sprintf($this->translate('Revision as of %s'), $toRevision['timestamp']->format('G:i:s, j F Y')), $this->url('scripto-revision-id', ['action' => 'show', 'revision-id' => $toRevision['revid']], true)); ?>
                    <?php echo sprintf(
                        $this->translate('by %s'),
                        $this->hyperlink($toRevision['user'], $this->url('scripto-user-contributions', ['action' => 'contributions', 'user-id' => $toRevision['user']], true))
                    ); ?></div>
                    <?php if ($toRevision['parsedcomment']): ?>
                    <div class="parsed-comment"><?php echo strip_tags($toRevision['parsedcomment']); ?></div>
                    <?php endif; ?>
                </th>
            </tr>
            <?php
                $completedHtml = '<div class="green">' . $this->translate('This revision marked as completed.') . '</div>';
                $approvedHtml = '<div class="green">' . $this->translate('This revision marked as approved.') . '</div>';
                $fromRevisionCompleted = ($fromRevision['revid'] === $sMedia->completedRevision()) ? $completedHtml : false;
                $fromRevisionApproved = ($fromRevision['revid'] === $sMedia->approvedRevision()) ? $approvedHtml : false;
                $toRevisionCompleted = ($toRevision['revid'] === $sMedia->completedRevision()) ? $completedHtml : false;
                $toRevisionApproved = ($toRevision['revid'] === $sMedia->approvedRevision()) ? $approvedHtml : false;
            ?>
            <?php if ($fromRevisionApproved || $fromRevisionCompleted || $toRevisionApproved || $toRevisionCompleted): ?>
            <tr>
                <th colspan="2">
                    <?php echo $fromRevisionCompleted; ?>
                    <?php echo $fromRevisionApproved; ?>
                </th>
                <th colspan="2">
                    <?php echo $toRevisionCompleted; ?>
                    <?php echo $toRevisionApproved; ?>
                </th>
            </tr>
            <?php endif; ?>
        </thead>
        <tbody>
            <?php if ($compare): ?>
            <?php echo $compare; ?>
            <?php else: ?>
            <tr><td colspan="4"><?php echo $this->translate('(No difference)'); ?></td></tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
