<?php
$this->scripto()->postTitle(sprintf($this->translate('Notes revision: %s'), $sMedia->link($media->displayTitle(), 'show-talk')));
$this->scripto()->postSubtitle(sprintf(
    $this->translate('Revision as of %s by %s'),
    $revision['timestamp']->format('G:i:s, j F Y'),
    $this->hyperlink($revision['user'], $this->url('scripto-user-contributions', ['action' => 'contributions', 'user-id' => $revision['user']], true))
));
?>
<div class="resource-content">
    <div class="browse-controls">
        <?php echo $this->hyperlink($this->translate('Return to revision history'), $this->url('scripto-talk-revision', ['action' => 'browse'], true)); ?>
    </div>
    <div class="media wikitext">
        <h3><?php echo $this->translate('Wikitext'); ?></h3>
        <textarea disabled aria-label="<?php echo $this->translate('Wikitext'); ?>"><?php echo $sMedia->pageWikitext(1, $revision['revid']); ?></textarea>
    </div>
    <div class="media html">
        <h3><?php echo $this->translate('HTML'); ?></h3>
        <?php $pageHtml = $sMedia->pageHtml(1, $revision['revid']); ?>
        <?php echo $pageHtml  ? $pageHtml : sprintf('<span>[%s]</span>', $this->translate('No HTML')); ?>
    </div>
</div>
