<?php
$label = isset($data['label']) ? $data['label'] : null;
$projectId = isset($data['project_id']) ? $data['project_id'] : null;
$select = $this->scripto()->getProjectSelect('project_id', $projectId);
$select->setAttributes(['data-name' => 'project_id']);
?>
<label>
    <?php echo $this->translate('Type'); ?>
    <input type="text" value="<?php echo $this->escapeHtml($this->translate($link->getName())); ?>" disabled>
</label>
<label class="required">
    <?php echo $this->translate('Label'); ?>
    <input type="text" data-name="label" value="<?php echo $this->escapeHtml($label); ?>" required>
</label>
<label class="required">
    <?php echo $this->translate('Project'); ?>
    <?php echo $this->formSelect($select); ?>
</label>
