<?php
$this->htmlElement('body')->appendAttribute('class', 'add');
$form->prepare();
?>

<?php echo $this->pageTitle($this->translate('New project'), 1, $this->translate('Scripto')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Add'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
