<?php
$this->ckEditor();
$this->htmlElement('body')->appendAttribute('class', 'scripto project add');
$form->prepare();
?>

<?php echo $this->pageTitle($this->translate('New project'), 1, $this->translate('Scripto')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'o-icon-private button',
        'title' => $this->translate('Make public'),
    ]); ?>
    <input type="hidden" name="o:is_public" value="0">
    <button><?php echo $this->translate('Add'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>

<script>
CKEDITOR.inline(document.getElementById('o-module-scripto-guidelines'));
</script>
