<?php
$this->htmlElement('body')->appendAttribute('class', 'browse');
?>

<?php echo $this->pageTitle($this->translate('Projects'), 1, $this->translate('Scripto')); ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Scripto\Api\Adapter\ScriptoProjectAdapter', 'create')): ?>
    <?php echo $this->hyperlink(
        $this->translate('Add new project'),
        $this->url('admin/scripto/add'),
        ['class' => 'button']
    ); ?>
    <?php endif; ?>
</div>

<?php if ($projects): ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
    [
        'label' => $this->translate('Date created'),
        'value' => 'created'
    ],
    [
        'label' => $this->translate('Last synced'),
        'value' => 'synced'
    ],
    [
        'label' => $this->translate('Last imported'),
        'value' => 'imported'
    ],
    [
        'label' => $this->translate('Title'),
        'value' => 'title'
    ],
]); ?>
</div>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Project title'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Date created'); ?></th>
            <th><?php echo $this->translate('Last synced'); ?></th>
            <th><?php echo $this->translate('Last imported'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($projects as $project): ?>
    <?php $owner = $project->owner(); ?>
        <tr>
            <td>
                <?php echo $project->link($project->title()); ?>
                <ul class="actions">
                    <?php if ($project->userIsAllowed('update')): ?>
                    <li><?php echo $project->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $this->translate('Edit'),
                    ]) ?></li>
                    <?php endif; ?>
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $project->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $owner ? $owner->link($owner->name()) : ''; ?></td>
            <td><?php echo $this->i18n()->dateFormat($project->created()); ?></td>
            <td><?php echo $this->i18n()->dateFormat($project->synced()); ?></td>
            <td><?php echo $this->i18n()->dateFormat($project->imported()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>
<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any Scripto projects.'); ?></p>
</div>
<?php endif; ?>
