<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'scripto project browse');
?>

<?php echo $this->pageTitle($this->translate('Projects'), 1, $this->translate('Scripto')); ?>

<div id="page-actions">
    <div id="page-action-menu">
    <?php if ($this->userIsAllowed('Scripto\Api\Adapter\ScriptoProjectAdapter', 'create')): ?>
      <?php echo $this->hyperlink(
          $this->translate('Add new project'),
          $this->url('admin/scripto-project', ['action' => 'add']),
          ['class' => 'button']
      ); ?>
    <?php endif; ?>
    </div>
</div>

<?php echo $this->scripto()->adminLoginBar(); ?>

<?php echo $this->scripto()->adminBreadcrumbs(); ?>

<?php if ($projects): ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
    [
        'label' => $this->translate('Date created'),
        'value' => 'created'
    ],
    [
        'label' => $this->translate('Last synced'),
        'value' => 'synced'
    ],
    [
        'label' => $this->translate('Last imported'),
        'value' => 'imported'
    ],
    [
        'label' => $this->translate('Title'),
        'value' => 'title'
    ],
]); ?>
</div>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Project'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Date created'); ?></th>
            <th><?php echo $this->translate('Last synced'); ?></th>
            <th><?php echo $this->translate('Last imported'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($projects as $project): ?>
    <?php $owner = $project->owner(); ?>
        <tr>
            <td>
                <?php echo $project->link($project->title()); ?>
                <?php if (!$project->isPublic()): ?>
                    <span class="o-icon-private" aria-label="<?php echo $this->translate('Private'); ?>"></span>
                <?php endif; ?>
                <ul class="actions">
                    <?php if ($project->userIsAllowed('update')): ?>
                    <li><?php echo $project->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $this->translate('Edit'),
                    ]) ?></li>
                    <?php endif; ?>
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $project->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'data-sidebar-selector' => '#show-details',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $owner ? $owner->link($owner->name()) : ''; ?></td>
            <td><?php echo $this->i18n()->dateFormat($project->created()); ?></td>
            <td><?php echo $this->i18n()->dateFormat($project->synced()); ?></td>
            <td><?php echo $this->i18n()->dateFormat($project->imported()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="show-details" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>
<div class="no-resources">
    <?php if ($this->userIsAllowed('Scripto\Api\Adapter\ScriptoProjectAdapter', 'create')): ?>
    <p><?php echo sprintf(
        $this->translate('No Scripto projects found. %s'),
        $this->hyperlink($this->translate('Add a new project.'), $this->url('admin/scripto-project', ['action' => 'add']))
    ); ?></p>
    <?php else: ?>
    <p><?php echo $this->translate('No Scripto projects found.'); ?></p>
    <?php endif; ?>
</div>
<?php endif; ?>
