<?php
$this->htmlElement('body')->appendAttribute('class', 'scripto project edit');
$form->prepare();
?>

<?php echo $this->pageTitle($this->translate('Edit project'), 1, $this->translate('Scripto'), $project->title()); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <a href="#" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
<?php echo $this->deleteConfirm($project, 'project'); ?>
