<?php
$this->htmlElement('body')->appendAttribute('class', 'show browse');
$this->pagination()->setFragment('project-items');
?>

<?php echo $this->pageTitle($this->translate('Review project'), 1, $this->translate('Scripto'), $project->title()); ?>

<div id="page-actions">
    <?php if ($project->userIsAllowed('update')): ?>
    <?php echo $project->link($this->translate('Edit project'), 'edit', ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php echo $this->sectionNav([
    'project-metadata' => $this->translate('Metadata'),
    'project-items' => $this->translate('Items'),
], 'view.show.section_nav', $project); ?>

<div id="project-metadata" class="active section">
    <div class="property">
        <h4><?php echo $this->translate('Title'); ?></h4>
        <div class="value"><?php echo $this->escapeHtml($project->title()); ?></div>
    </div>
    <div class="property">
        <h4><?php echo $this->translate('Description'); ?></h4>
        <div class="value"><?php echo $this->escapeHtml($project->description()); ?></div>
    </div>
    <div class="property">
        <h4><?php echo $this->translate('Item set'); ?></h4>
        <?php $itemSet = $project->itemSet(); ?>
        <div class="value"><?php echo $itemSet->link($itemSet->displayTitle()); ?></div>
    </div>
    <div class="property">
        <h4><?php echo $this->translate('Property'); ?></h4>
        <?php $property = $project->property(); ?>
        <div class="value"><?php echo sprintf('%s : %s', $property->vocabulary()->label(), $property->label()); ?></div>
    </div>
    <div class="property">
        <h4><?php echo $this->translate('Language tag'); ?></h4>
        <div class="value"><?php echo $this->escapeHtml($project->lang()); ?></div>
    </div>
    <div class="property">
        <h4><?php echo $this->translate('Date created'); ?></h4>
        <div class="value"><?php echo $this->i18n()->dateFormat($project->created(), 'long', 'medium'); ?></div>
    </div>
    <div class="property">
        <h4><?php echo $this->translate('Date synced'); ?></h4>
        <?php $synced = $project->synced(); ?>
        <div class="value"><?php echo $synced ? $this->i18n()->dateFormat($project->synced(), 'long', 'medium') : $this->translate('Not synced'); ?></div>
    </div>
    <div class="property">
        <h4><?php echo $this->translate('Date imported'); ?></h4>
        <?php $imported = $project->imported(); ?>
        <div class="value"><?php echo $imported ? $this->i18n()->dateFormat($project->imported(), 'long', 'medium') : $this->translate('Not imported'); ?></div>
    </div>
</div>

<div id="project-items" class="section">
    <div class="browse-controls">
        <?php echo $this->pagination(); ?>
        <?php echo $this->sortSelector([
            [
                'label' => $this->translate('Date synced'),
                'value' => 'synced'
            ],
            [
                'label' => $this->translate('Last edited'),
                'value' => 'edited'
            ],
        ]); ?>
        <select name="filter">
            <option value="">All</option>
            <option value="is_approved">Is approved</option>
            <option value="is_not_approved">Is not approved</option>
        </select>
    </div>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Item title'); ?></th>
                <th><?php echo $this->translate('Date synced'); ?></th>
                <th><?php echo $this->translate('Last edited'); ?></th>
                <th><?php echo $this->translate('Media count'); ?></th>
                <th><?php echo $this->translate('Status'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($sItems as $sItem): ?>
            <tr>
                <td>
                    <?php echo $sItem->link($sItem->item()->displayTitle()); ?>
                    <ul class="actions">
                        <li><?php echo $this->hyperlink('', '#', [
                            'data-sidebar-content-url' => $sItem->url('show-details'),
                            'class' => 'o-icon-more sidebar-content',
                            'title' => $this->translate('Details'),
                        ]); ?></li>
                    </ul>
                </td>
                <td><?php echo $this->i18n()->dateFormat($sItem->synced()); ?></td>
                <td><?php echo $this->i18n()->dateFormat($sItem->edited()); ?></td>
                <td><?php echo number_format($sItem->mediaCount()); ?></td>
                <td><?php echo $this->translate($sItem->status()); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div class="browse-controls">
        <?php echo $this->pagination(); ?>
    </div>
</div>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>
