<h3><?php echo $this->translate('Project metadata'); ?></h3>
<div class="meta-group">
    <h4><?php echo $this->translate('Project'); ?></h4>
    <div class="value"><?php echo $project->link($project->title()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Description'); ?></h4>
    <?php $description = $project->description(); ?>
    <div class="value"><?php echo $description ? $this->escapeHtml($project->description()) : $this->translate('No description'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Item set'); ?></h4>
    <?php $itemSet = $project->itemSet(); ?>
    <div class="value"><?php echo $itemSet ? $itemSet->link($itemSet->displayTitle()) : $this->translate('Not set'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Media types'); ?></h4>
    <?php if ($mediaTypes = $project->mediaTypes()): ?>
    <div class="value">
    <?php foreach ($mediaTypes as $mediaType): ?>
    <?php echo $mediaType; ?><br/>
    <?php endforeach; ?>
    </div>
    <?php else: ?>
    <div class="value"><?php echo $this->translate('All'); ?></div>
    <?php endif; ?>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Property'); ?></h4>
    <?php $property = $project->property(); ?>
    <div class="value"><?php echo $property ? sprintf('%s : %s', $property->vocabulary()->label(), $property->label()) : $this->translate('Not set'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Language tag'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($project->lang()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Import target'); ?></h4>
    <div class="value">
        <?php if ('media' === $project->importTarget()): ?>
        <?php echo $this->translate('Media'); ?>
        <?php elseif ('item' === $project->importTarget()): ?>
        <?php echo $this->translate('Item'); ?>
        <?php else: ?>
        <?php echo $this->translate('Item and media'); ?>
        <?php endif; ?>
    </div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Browse layout'); ?></h4>
    <div class="value">
    <?php if ('list' === $project->browseLayout()): ?>
    <?php echo $this->translate('List'); ?>
    <?php else: ?>
    <?php echo $this->translate('Grid'); ?>
    <?php endif; ?>
    </div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Item type'); ?></h4>
    <div class="value"><?php echo $this->scripto()->translate($project->itemType(), 'Item'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Media type'); ?></h4>
    <div class="value"><?php echo $this->scripto()->translate($project->mediaType(), 'Media'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Content type'); ?></h4>
    <div class="value"><?php echo $this->scripto()->translate($project->contentType(), 'Content'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Visibility'); ?></h4>
    <div class="value"><?php echo ($project->isPublic()) ? $this->translate('Public') : $this->translate('Private'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Owner'); ?></h4>
    <?php $owner = $project->owner(); ?>
    <div class="value"><?php echo $owner ? $owner->link($owner->name()) : $this->translate('No owner'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Date created'); ?></h4>
    <div class="value"><?php echo $this->i18n()->dateFormat($project->created(), 'long', 'medium'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Last synced'); ?></h4>
    <?php $synced = $project->synced(); ?>
    <div class="value"><?php echo $synced ? $this->i18n()->dateFormat($project->synced(), 'long', 'medium') : $this->translate('Not synced'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Last imported'); ?></h4>
    <?php $imported = $project->imported(); ?>
    <div class="value"><?php echo $imported ? $this->i18n()->dateFormat($project->imported(), 'long', 'medium') : $this->translate('Not imported'); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->scripto()->translate($project->itemType(), 'Total item count'); ?></h4>
    <div class="value"><?php echo number_format($project->itemCount()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->scripto()->translate($project->itemType(), 'Is approved item count'); ?></h4>
    <div class="value"><?php echo number_format($project->isApprovedItemCount()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->scripto()->translate($project->itemType(), 'Is not approved item count'); ?></h4>
    <div class="value"><?php echo number_format($project->isNotApprovedItemCount()); ?></div>
</div>
