<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'scripto dashboard');
?>

<?php echo $this->pageTitle($this->translate('Dashboard'), 1, $this->translate('Scripto')); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <a href="#" class="expand button" aria-label="<?php echo $this->translate('Expand'); ?>"><?php echo $this->translate('Actions'); ?></a>
        <ul class="collapsible">
            <li><?php echo $this->hyperlink($this->translate('Browse projects'), $this->url('admin/scripto-project')); ?></li>
            <li><?php echo $this->hyperlink($this->translate('Add new project'), $this->url('admin/scripto-project', ['action' => 'add'])); ?></li>
            <li><?php echo $this->hyperlink($this->translate('Browse users'), $this->url('admin/scripto-user')); ?></li>
        </ul>
    </div>
</div>

<?php echo $this->scripto()->adminLoginBar(); ?>

<div class="dashboard-row">

    <div class="recent-projects panel">
        <h4><?php echo $this->translate('Your projects'); ?> <?php echo $this->hyperlink($this->translate('View all projects'), $this->url('admin/scripto-project'), ['class' => 'button']); ?></h4>
        <?php if ($projects): ?>
        <ul>
        <?php foreach ($projects as $project): ?>
            <li><?php echo $project->link($project->title()); ?></li>
        <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <p><?php echo sprintf(
            $this->translate('No projects found. %s'),
            sprintf(
                '<a href="%s">%s</a>',
                $this->escapeHtml($this->url('admin/scripto-project', ['action' => 'add'])),
                $this->translate('Add a project here.')
            )
        ); ?></p>
        <?php endif; ?>
    </div>

    <div class="recent-contributions panel">
        <h4>
            <?php echo $this->translate('Your recent contributions'); ?>
            <?php if (!isset($user['invalid'])): ?>
            <?php echo $this->hyperlink($this->translate('View all your contributions'), $this->url('admin/scripto-user-id', ['user-id' => $user['name']]), ['class' => 'button']); ?>
            <?php endif; ?>
        </h4>
        <?php if (!isset($user['invalid']) && $userCons): ?>
        <ul>
        <?php foreach ($userCons as $userCon): ?>
            <?php
            $date = $this->i18n()->dateFormat($userCon['timestamp'], 'short', 'short');
            $sMedia = isset($userCon['scripto_media']) ? $userCon['scripto_media'] : null;
            $sItem = $sMedia ? $sMedia->scriptoItem() : null;
            $project = $sItem ? $sItem->scriptoProject() : null;
            ?>
            <li>
                <?php echo sprintf(
                    '%s (%s)',
                    $sMedia
                        ? $this->hyperlink($sItem->item()->displayTitle(), $this->url('admin/scripto-revision-id', [
                            'project-id' => $project->id(),
                            'item-id' => $sItem->item()->id(),
                            'media-id' => $sMedia->media()->id(),
                            'revision-id' => $userCon['revid'],
                        ]))
                        : $userCon['title'],
                    $date
                ); ?>
                <?php echo sprintf('(%s%s)', 0 < $userCon['sizediff'] ? '+' : '', number_format($userCon['sizediff'])); ?>
                <i><?php echo $userCon['parsedcomment']; ?></i>
            </li>
        <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <p><?php echo $this->translate('No contributions found. Do you need to log in to Scripto?'); ?></p>
        <?php endif; ?>
    </div>

</div>
