<?php
$title = sprintf('%s · %s', $this->translate('Scripto'), $this->setting('installation_title', 'Omeka S'));

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($title);
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/public-app.css', 'Scripto'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/public-app.js', 'Scripto'));
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <header class="site-header" role="banner">
        <div class="wrapper">
            <?php echo $this->hyperlink($title, $this->url('scripto'), ['class' => 'site-title']); ?>
            <nav class="site-nav">
                <input type="checkbox" id="nav-trigger" class="nav-trigger" aria-label="<?php echo $this->translate('Toggle menu'); ?>"/>
                <label for="nav-trigger">
                    <span class="menu-icon"></span>
                </label>
                <div class="trigger">
                    <?php echo $this->hyperlink($this->translate('Projects'), $this->url('scripto-project'), ['class' => 'page-link']); ?>
                    <?php echo $this->scripto()->loginBar(); ?>
                    <?php if (!$this->scripto()->apiClient()->userIsLoggedIn()): ?>
                    <?php echo $this->hyperlink($this->translate('Create account'), $this->url('scripto', ['action' => 'create-account']), ['class' => 'page-link']); ?>
                    <?php endif; ?>
                </div>
            </nav>
        </div>
        <?php if (isset($project)): ?>
        <?php
        $searchAction = isset($sItem) ? $sItem->url() : $project->url();
        $searchQuery = $this->params()->fromQuery('search');
        ?>
        <form id="scripto-search" class="wrapper" action="<?php echo $this->escapeHtml($searchAction); ?>">
            <input type="text" name="search" value="<?php echo $this->escapeHtml($searchQuery); ?>" aria-label="<?php echo $this->escapeHtml($this->translate('Query')); ?>">
            <button type="submit" class="o-icon-search" aria-label="<?php echo $this->escapeHtml($this->translate('Search')); ?>"></button>
        </form>
        <nav class="project-nav wrapper">
            <h2><?php echo $project->link($project->title()); ?></h2>
            <ul>
                <li><?php echo $project->link($this->translate('Project guidelines'), 'guidelines'); ?></li>
                <li><?php echo $project->link($this->translate('Browse items')); ?></li>
                <?php if (isset($sItem)): ?>
                <li><?php echo $sItem->link($this->translate('Browse media')); ?></li>
                <?php endif; ?>
                <?php if (isset($sMedia)): ?>
                <li><?php echo $sMedia->link($this->translate('View media')); ?></li>
                <li><?php echo $this->hyperlink($this->translate('Browse revisions'), $this->url('scripto-revision', ['action' => 'browse'], true)); ?></li>
                <?php endif; ?>
            </ul>
        </nav>
        <?php endif; ?>
    </header>
    <body>
        <main class="page-content" aria-label="<?php echo $this->escapeHtml($this->translate('Content')); ?>">
            <div class="wrapper">
                <?php echo $this->messages(); ?>
                <article class="post">
                    <header class="post-header">
                        <?php if ($this->scripto()->postTitle()): ?>
                        <h1 class="post-title"><?php echo $this->scripto()->postTitle(); ?></h1>
                        <?php endif; ?>
                        <?php if ($this->scripto()->postSubtitle()): ?>
                        <h2 class="post-subtitle"><?php echo $this->scripto()->postSubtitle(); ?></h2>
                        <?php endif; ?>
                    </header>
                    <div class="post-content">
                        <?php echo $this->content; ?>
                    </div>
                </article>
            </div>
        </main>
        <footer class="site-footer h-card">
            <div class="wrapper">
                <h2 class="footer-heading"><?php echo $title; ?></h2>
                <div class="footer-col-wrapper">
                    <div class="footer-col footer-col-1"></div>
                    <div class="footer-col footer-col-2">
                        <ul class="social-media-list"></ul>
                    </div>
                    <div class="footer-col footer-col-3"></div>
                </div>
            </div>
        </footer>
    </body>
</html>
