<?php
$title = sprintf('%s · %s', $this->translate('Scripto'), $this->setting('installation_title', 'Omeka S'));

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($title);
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/public-app.css', 'Scripto'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/public-app.js', 'Scripto'));
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <header class="site-header" role="banner">
        <div class="wrapper">
            <?php echo $this->hyperlink($title, $this->url('scripto'), ['class' => 'site-title']); ?>
            <nav class="site-nav">
                <input type="checkbox" id="nav-trigger" class="nav-trigger" />
                <label for="nav-trigger">
                    <span class="menu-icon">
                        <svg viewBox="0 0 18 15" width="18px" height="15px">
                            <path d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.032C17.335,0,18,0.665,18,1.484L18,1.484z M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.032C17.335,6.031,18,6.696,18,7.516L18,7.516z M18,13.516C18,14.335,17.335,15,16.516,15H1.484 C0.665,15,0,14.335,0,13.516l0,0c0-0.82,0.665-1.483,1.484-1.483h15.032C17.335,12.031,18,12.695,18,13.516L18,13.516z"/>
                        </svg>
                    </span>
                </label>
                <div class="trigger">
                    <?php echo $this->hyperlink($this->translate('Projects'), $this->url('scripto-project'), ['class' => 'page-link']); ?>
                    <?php echo $this->scripto()->loginBar(); ?>
                </div>
            </nav>
        </div>
        <?php if (isset($project)): ?>
        <?php
        $searchAction = isset($sItem) ? $sItem->url() : $project->url();
        $searchQuery = $this->params()->fromQuery('search');
        ?>
        <form id="scripto-search" class="wrapper" action="<?php echo $this->escapeHtml($searchAction); ?>">
            <input type="text" name="search" value="<?php echo $this->escapeHtml($searchQuery); ?>" aria-label="<?php echo $this->escapeHtml($this->translate('Query')); ?>">
            <button type="submit" class="o-icon-search" aria-label="<?php echo $this->escapeHtml($this->translate('Search')); ?>"></button>
        </form>
        <nav class="project-nav wrapper">
            <h2><?php echo $project->link($project->title()); ?></h2>
            <ul>
                <li><?php echo $project->link($this->translate('Items')); ?></li>
                <li><?php echo $project->link($this->translate('Transcription Guidelines'), 'guidelines'); ?></li>
                <?php if (isset($sMedia)): ?>
                <li><?php echo $this->hyperlink($this->translate('Revision history'), $this->url('scripto-revision', ['action' => 'browse'], true)); ?></li>
                <?php endif; ?>
            </ul>
        </nav>
        <?php endif; ?>
    </header>
    <body>
        <main class="page-content" aria-label="<?php echo $this->escapeHtml($this->translate('Content')); ?>">
            <div class="wrapper">
                <?php echo $this->messages(); ?>
                <?php echo $this->content; ?>
            </div>
        </main>
        <footer class="site-footer h-card">
            <div class="wrapper">
                <h2 class="footer-heading"><?php echo $title; ?></h2>
                <div class="footer-col-wrapper">
                    <div class="footer-col footer-col-1"></div>
                    <div class="footer-col footer-col-2">
                        <ul class="social-media-list"></ul>
                    </div>
                    <div class="footer-col footer-col-3"></div>
                </div>
            </div>
        </footer>
    </body>
</html>
