<?php
$this->scripto()->postTitle(sprintf($this->translate('Contributions by %s'), $user['name']));
?>
<div class="resource-content">
    <div class="browse-controls">
        <?php echo $this->scripto()->mediawikiPagination(); ?>
    </div>
    <table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Revision'); ?></th>
                <th></th>
                <th><?php echo $this->translate('Media #'); ?></th>
                <th><?php echo $this->translate('Type'); ?></th>
                <th><?php echo $this->translate('Item'); ?></th>
                <th><?php echo $this->translate('Project'); ?></th>
                <th><?php echo $this->translate('Size'); ?></th>
                <th><?php echo $this->translate('Comment'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($userCons as $userCon): ?>
        <?php
        $date = $userCon['timestamp']->format('G:i, j F Y');
        $flags = array_filter([
            $userCon['new'] ? $this->translate('new') : null,
            $userCon['top'] ? $this->translate('current') : null,
        ]);
        $sMedia = isset($userCon['scripto_media']) ? $userCon['scripto_media'] : null;
        $sItem = $sMedia ? $sMedia->scriptoItem() : null;
        $project = $sItem ? $sItem->scriptoProject() : null;
        $isTalk = (1 === $userCon['ns']);
        ?>
            <tr>
                <td class="revision">
                    <?php echo $sMedia
                    ? $this->hyperlink($date, $this->url(
                        $isTalk ? 'scripto-talk-revision-id' : 'scripto-revision-id',
                        [
                            'action' => 'show',
                            'project-id' => $project->id(),
                            'item-id' => $sItem->item()->id(),
                            'media-id' => $sMedia->media()->id(),
                            'revision-id' => $userCon['revid'],
                        ],
                        true
                    ))
                    : $date; ?>
                    <span class="flags"><?php echo $flags ? sprintf(' (%s)', implode(', ', $flags)) : null; ?></span>
                </td>
                <td class="diff-hist">
                    <?php echo $sMedia
                    ? sprintf(
                        '(%s | %s)',
                        $userCon['parentid']
                            ? $this->hyperlink($this->translate('diff'), $this->url(
                                $isTalk ? 'scripto-talk-revision-compare' : 'scripto-revision-compare',
                                [
                                    'action' => 'compare',
                                    'project-id' => $project->id(),
                                    'item-id' => $sItem->item()->id(),
                                    'media-id' => $sMedia->media()->id(),
                                    'from-revision-id' => $userCon['parentid'],
                                    'to-revision-id' => $userCon['revid'],
                                ],
                                true
                            ))
                            : $this->translate('diff'),
                        $this->hyperlink($this->translate('hist'), $this->url(
                            $isTalk ? 'scripto-talk-revision' : 'scripto-revision',
                            [
                                'action' => 'browse',
                                'project-id' => $project->id(),
                                'item-id' => $sItem->item()->id(),
                                'media-id' => $sMedia->media()->id(),
                            ],
                            true
                        ))
                    )
                    : ''; ?>
                </td>
                <td class="number">
                    <?php echo $sMedia
                    ? $isTalk
                        ? $this->hyperlink(sprintf($this->scripto()->translate($project->mediaType(), 'Media #%s notes'), $sMedia->position()), $sMedia->url('talk'))
                        : $this->hyperlink(sprintf($this->scripto()->translate($project->mediaType(), 'Media #%s'), $sMedia->position()), $sMedia->url())
                    : $this->translate('n/a'); ?>
                </td>
                <td><?php echo $project ? $this->scripto()->translate($project->itemType(), 'Item') : $this->translate('n/a'); ?></td>
                <td class="item"><?php echo $sItem ? $sItem->link($sItem->item()->displayTitle()) : $userCon['title']; ?></td>
                <td class="project"><?php echo $project ? $project->link($project->title()) : $this->translate('n/a'); ?></td>
                <td><?php echo sprintf(
                    $this->translate('%s bytes (%s)'),
                    number_format($userCon['size']),
                    sprintf(
                        '<span style="color: %s;">%s%s</span>',
                        0 < $userCon['sizediff'] ? 'green' : (0 > $userCon['sizediff'] ? 'red' : 'inherit'),
                        0 < $userCon['sizediff'] ? '+' : null,
                        number_format($userCon['sizediff'])
                    )
                ); ?></td>
                <td class="comment"><i><?php echo strip_tags($userCon['parsedcomment']); ?></i></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
