<article class="post">
    <header class="post-header">
        <h1 class="post-title"><?php echo $this->translate('Your watchlist'); ?></h1>
    </header>
    <div class="post-content">
        <div class="browse-controls">
            <?php echo $this->scripto()->mediawikiPagination(); ?>
            <?php echo $this->scripto()->watchlistTimePeriodSelect(); ?>
        </div>
        <table class="tablesaw" data-tablesaw-mode="stack">
            <thead>
                <tr>
                    <th><?php echo $this->translate('Item'); ?></th>
                    <th><?php echo $this->translate('Media #'); ?></th>
                    <th><?php echo $this->translate('Project'); ?></th>
                    <th><?php echo $this->translate('Revision'); ?></th>
                    <th><?php echo $this->translate('Size'); ?></th>
                    <th><?php echo $this->translate('User'); ?></th>
                    <th class="comment"><?php echo $this->translate('Comment'); ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($watchlist as $page): ?>
            <?php
            $date = $page['timestamp']->format('G:i, j F Y');
            $sizeDiff = $page['newlen'] - $page['oldlen'];
            $sMedia = isset($page['scripto_media']) ? $page['scripto_media'] : null;
            $sItem = $sMedia ? $sMedia->scriptoItem() : null;
            $project = $sItem ? $sItem->scriptoProject() : null;
            ?>
                <tr>
                    <td><?php echo $sItem ? $sItem->link($sItem->item()->displayTitle()) : $page['title']; ?></td>
                    <td>
                        <?php echo $sMedia
                        ? $this->hyperlink(sprintf($this->translate('Media #%s'), $sMedia->position()), $sMedia->url())
                        : $this->translate('n/a'); ?>
                    </td>
                    <td><?php echo $project ? $project->link($project->title()) : $this->translate('n/a'); ?></td>
                    <td>
                        <?php echo $sMedia
                        ? $this->hyperlink($date, $this->url('scripto-revision-id', [
                            'project-id' => $project->id(),
                            'item-id' => $sItem->item()->id(),
                            'media-id' => $sMedia->media()->id(),
                            'revision-id' => $page['revid'],
                        ]))
                        : $date; ?>
                    </td>
                    <td><?php echo sprintf('%s bytes (%s)', number_format($page['newlen']), sprintf('%s%s', 0 < $sizeDiff ? '+' : '', number_format($sizeDiff))); ?></td>
                    <td><?php echo $page['user']; ?></td>
                    <td><i><?php echo strip_tags($page['parsedcomment']); ?></i></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</article>
