<?php
$this->headScript()->appendFile($this->assetUrl('js/common/watchlist.js', 'Scripto'));
$this->scripto()->postTitle($this->translate('Your watchlist'));
?>
<div class="resource-content">
    <div class="browse-controls">
        <?php echo $this->scripto()->watchlistTimePeriodSelect(); ?>
        <?php echo $this->scripto()->mediawikiPagination(); ?>
    </div>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Media #'); ?></th>
                <th><?php echo $this->translate('Type'); ?></th>
                <th><?php echo $this->translate('Item'); ?></th>
                <th><?php echo $this->translate('Project'); ?></th>
                <th><?php echo $this->translate('Revision'); ?></th>
                <th></th>
                <th><?php echo $this->translate('Size'); ?></th>
                <th><?php echo $this->translate('User'); ?></th>
                <th class="comment"><?php echo $this->translate('Comment'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($watchlist as $page): ?>
        <?php
        $date = $page['timestamp']->format('G:i, j F Y');
        $sizeDiff = $page['newlen'] - $page['oldlen'];
        $sMedia = isset($page['scripto_media']) ? $page['scripto_media'] : null;
        $sItem = $sMedia ? $sMedia->scriptoItem() : null;
        $project = $sItem ? $sItem->scriptoProject() : null;
        $isTalk = (1 === $page['ns']);
        ?>
            <tr>
                <td>
                    <?php echo $sMedia
                    ? $isTalk
                        ? $this->hyperlink(sprintf($this->scripto()->translate($project->mediaType(), 'Media #%s notes'), $sMedia->position()), $sMedia->url('talk'))
                        : $this->hyperlink(sprintf($this->scripto()->translate($project->mediaType(), 'Media #%s'), $sMedia->position()), $sMedia->url())
                    : $this->translate('n/a'); ?>
                </td>
                <td><?php echo $project ? $this->scripto()->translate($project->itemType(), 'Item') : $this->translate('n/a'); ?></td>
                <td><?php echo $sItem ? $sItem->link($sItem->item()->displayTitle()) : $page['title']; ?></td>
                <td><?php echo $project ? $project->link($project->title()) : $this->translate('n/a'); ?></td>
                <td>
                    <?php echo $sMedia
                    ? $this->hyperlink($date, $this->url(
                        $isTalk ? 'scripto-talk-revision-id' : 'scripto-revision-id',
                        [
                            'action' => 'show',
                            'project-id' => $project->id(),
                            'item-id' => $sItem->item()->id(),
                            'media-id' => $sMedia->media()->id(),
                            'revision-id' => $page['revid'],
                        ],
                        true
                    ))
                    : $date; ?>
                </td>
                <td>
                    <?php echo $sMedia
                    ? sprintf(
                        '(%s | %s)',
                        $page['old_revid']
                            ? $this->hyperlink($this->translate('diff'), $this->url(
                                $isTalk ? 'scripto-talk-revision-compare' : 'scripto-revision-compare',
                                [
                                    'action' => 'compare',
                                    'project-id' => $project->id(),
                                    'item-id' => $sItem->item()->id(),
                                    'media-id' => $sMedia->media()->id(),
                                    'from-revision-id' => $page['old_revid'],
                                    'to-revision-id' => $page['revid'],
                                ],
                                true
                            ))
                            : $this->translate('diff'),
                        $this->hyperlink($this->translate('hist'), $this->url(
                            $isTalk ? 'scripto-talk-revision' : 'scripto-revision',
                            [
                                'action' => 'browse',
                                'project-id' => $project->id(),
                                'item-id' => $sItem->item()->id(),
                                'media-id' => $sMedia->media()->id(),
                            ],
                            true
                        ))
                    )
                    : ''; ?>
                </td>
                <td><?php echo sprintf(
                    $this->translate('%s bytes (%s)'),
                    number_format($page['newlen']),
                    sprintf(
                        '<span style="color: %s;">%s%s</span>',
                        0 < $sizeDiff ? 'green' : (0 > $sizeDiff ? 'red' : 'inherit'),
                        0 < $sizeDiff ? '+' : '',
                        number_format($sizeDiff)
                    )
                ); ?></td>
                <td><?php echo $this->hyperlink($page['user'], $this->url('scripto-user-contributions', ['action' => 'contributions', 'user-id' => $page['user']], true)); ?></td>
                <td><i><?php echo strip_tags($page['parsedcomment']); ?></i></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
