<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'scripto item review media browse no-actions');
?>

<?php echo $this->pageTitle($sItem->item()->displayTitle(), 1, $this->scripto()->translate($project->itemType(), 'Scripto: Item'), $this->scripto()->translate($project->mediaType(), 'Batch edit medias')); ?>

<?php echo $this->scripto()->adminLoginBar(); ?>

<?php echo $this->scripto()->adminBreadcrumbs(); ?>

<?php echo $this->form()->openTag($form); ?>

<?php foreach ($sMedias as $sMedia): ?>
<input type="hidden" name="resource_ids[]" value="<?php echo $sMedia->id(); ?>">
<?php endforeach; ?>

<div id="page-actions">
    <a class="button" href="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">Cancel</a>
    <input type="submit" name="batch_edit" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>">
</div>

<?php echo $this->formRow($form->get('is_completed')); ?>

<?php echo $this->formRow($form->get('is_approved')); ?>

<?php if ($this->scripto()->apiClient()->userIsInGroup('sysop')): ?>
<?php echo $this->formRow($form->get('protection_level')); ?>
<?php echo $this->formRow($form->get('protection_expiry')); ?>
<?php endif; ?>

<?php if ($this->scripto()->apiClient()->userIsLoggedIn()): ?>
<?php echo $this->formRow($form->get('is_watched')); ?>
<?php endif; ?>

<?php echo $this->formElement($form->get('mediabatchform_csrf')); ?>

<?php echo $this->form()->closeTag(); ?>

<div class="sidebar always-open">
    <h3><?php echo $this->scripto()->translate($project->mediaType(), 'Affected medias'); ?></h3>
    <p><?php echo sprintf($this->scripto()->translate($project->mediaType(), 'You are editing the following %s medias'), count($sMedias)); ?></p>
    <ul class="batch-selected">
        <?php foreach ($sMedias as $sMedia): ?>
        <li><?php echo $sMedia->link($sMedia->media()->displayTitle(), null, ['target' => '_blank']); ?></li>
        <?php endforeach; ?>
    </ul>
</div>
