<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'browse'); 
?>

<?php echo $this->pageTitle($this->translate('Review item'), 1, $this->translate('Scripto'), $sItem->item()->displayTitle()); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <a href="#" class="expand button" aria-label="<?php echo $this->translate('Expand'); ?>"><?php echo $this->translate('Actions'); ?></a>
        <ul class="collapsible">
            <li><a href="#" class="sidebar-content" data-sidebar-selector="#scripto-item-metadata"><?php echo $this->translate('View item metadata'); ?></a></li>
        </ul>
    </div>
</div>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Projects'), $this->url('admin/scripto-project')); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Review project'), $this->url('admin/scripto-project-id', ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    <span class="current"><?php echo $this->translate('Review item'); ?></span>
</div>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
        [
            'label' => $this->translate('Position'),
            'value' => 'position'
        ],
        [
            'label' => $this->translate('Last synced'),
            'value' => 'synced'
        ],
        [
            'label' => $this->translate('Last edited'),
            'value' => 'edited'
        ],
        [
            'label' => $this->translate('Last completed'),
            'value' => 'completed'
        ],
        [
            'label' => $this->translate('Last approved'),
            'value' => 'approved'
        ],
    ]); ?>
    <?php echo $this->filterSelector([
        [
            'label' => $this->translate('Is edited'),
            'value' => 'is_edited',
        ],
        [
            'label' => $this->translate('Is not edited'),
            'value' => 'is_not_edited',
        ],
        [
            'label' => $this->translate('Is completed'),
            'value' => 'is_edited',
        ],
        [
            'label' => $this->translate('Is not completed'),
            'value' => 'is_not_completed',
        ],
        [
            'label' => $this->translate('Is approved'),
            'value' => 'is_approved',
        ],
        [
            'label' => $this->translate('Is not approved'),
            'value' => 'is_not_approved',
        ],
        [
            'label' => $this->translate('Is edited after approved'),
            'value' => 'is_edited_after_approved',
        ],
        [
            'label' => $this->translate('Is edited after imported'),
            'value' => 'is_edited_after_imported',
        ],
        [
            'label' => $this->translate('Is synced after imported'),
            'value' => 'is_synced_after_imported',
        ],
    ]); ?>
</div>

<?php if ($sMedia): ?>

<?php echo $this->form()->openTag($batchForm); ?>

<div class="batch-inputs">
    <?php echo $this->formElement($batchForm->get('batch-review-action')); ?>
    <?php echo $this->formElement($batchForm->get('batchreviewmediaform_csrf')); ?>
    <div class="batch-actions">
        <button type="button" class="default active" disabled="true"><?php echo $this->translate('Go'); ?></button>
        <?php echo $this->formElement($batchForm->get('batch-review-submit')); ?>
    </div>
</div>

<table class="tablesaw scripto-media batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><input type="checkbox" class="select-all">#</th>
            <th><?php echo $this->translate('Media'); ?></th>
            <th><?php echo $this->translate('Last synced'); ?></th>
            <th><?php echo $this->translate('Last edited'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($sMedia as $index => $sMedia): ?>
        <tr>
            <td><input type="checkbox" name="resource_ids[]" value="<?php echo $sMedia->id(); ?>"> <?php echo $index + 1; ?></td>
            <td>
                <?php echo $sMedia->linkPretty('square', null, 'review'); ?>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $sMedia->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $this->i18n()->dateFormat($sMedia->synced()); ?></td>
            <td><?php echo $this->i18n()->dateFormat($sMedia->edited()); ?></td>
            <td><?php echo $this->translate($sMedia->status()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->form()->closeTag(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>
<div class="no-resources">
    <p><?php echo sprintf(
        $this->translate('No Scripto media found. %s'),
        sprintf(
            '<a href="%s">%s</a>',
            $this->url('admin/scripto-project-id', ['controller' => 'project', 'action' => 'show-actions'], true),
            $this->translate('Do you need to sync the project?')
        )
    ); ?></p>
</div>
<?php endif; ?>

<div id="scripto-item-metadata" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Item metadata'); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Scripto project'); ?></h4>
        <div class="value"><?php echo $project->link($project->title()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Status'); ?></h4>
        <div class="value"><?php echo $this->translate($sItem->status()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Date synced'); ?></h4>
        <div class="value"><?php echo $this->i18n()->dateFormat($sItem->synced(), 'long', 'medium'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Last edited'); ?></h4>
        <?php $edited = $sItem->edited(); ?>
        <div class="value"><?php echo $edited ? $this->i18n()->dateFormat($sItem->edited(), 'long', 'medium') : $this->translate('Not edited'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Omeka item'); ?></h4>
        <div class="value"><?php echo $item->link($item->displayTitle()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Omeka item description'); ?></h4>
        <?php $description = $item->displayDescription(); ?>
        <div class="value"><?php echo $description ? nl2br($this->escapeHtml($description)) : $this->translate('No description'); ?></div>
    </div>
</div>

<script>
var batchForm = $('#batch-form');
var batchSelectedOptions = batchForm.find('option[value$="-selected"]');
var batchSubmit = batchForm.find('input.batch-review-submit');
batchForm.on('change', ':checkbox', function(e) {
    if (batchForm.find(':checkbox:checked').length > 0) {
        // at least one checkbox is checked
        batchSelectedOptions.prop('disabled', false);
    } else {
        // no checkboxes are checked
        batchSelectedOptions.prop('disabled', true);
        batchSubmit.hide();
    }
});
batchForm.on('change', 'select.batch-actions-select', function(e) {
    if ('default' === $(this).find(':selected').val()) {
        batchSubmit.hide();
    } else {
        batchSubmit.show();
    }
});
</script>
