<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'browse'); 
?>

<?php echo $this->pageTitle($this->translate('Review item'), 1, $this->translate('Scripto'), $sItem->item()->displayTitle()); ?>

<div id="page-actions">
    <?php echo $sItem->scriptoProject()->link($this->translate('Review project'), 'show', ['class' => 'button']); ?>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ScriptoItem')->menu(); ?>
</nav>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
        [
            'label' => $this->translate('Position'),
            'value' => 'position'
        ],
        [
            'label' => $this->translate('Last synced'),
            'value' => 'synced'
        ],
        [
            'label' => $this->translate('Last edited'),
            'value' => 'edited'
        ],
        [
            'label' => $this->translate('Last completed'),
            'value' => 'completed'
        ],
        [
            'label' => $this->translate('Last approved'),
            'value' => 'approved'
        ],
    ]); ?>
    <?php echo $this->filterSelector([
        [
            'label' => $this->translate('Is edited'),
            'value' => 'is_edited',
        ],
        [
            'label' => $this->translate('Is not edited'),
            'value' => 'is_not_edited',
        ],
        [
            'label' => $this->translate('Is completed'),
            'value' => 'is_edited',
        ],
        [
            'label' => $this->translate('Is not completed'),
            'value' => 'is_not_completed',
        ],
        [
            'label' => $this->translate('Is approved'),
            'value' => 'is_approved',
        ],
        [
            'label' => $this->translate('Is not approved'),
            'value' => 'is_not_approved',
        ],
        [
            'label' => $this->translate('Is edited after approved'),
            'value' => 'is_edited_after_approved',
        ],
        [
            'label' => $this->translate('Is edited after imported'),
            'value' => 'is_edited_after_imported',
        ],
        [
            'label' => $this->translate('Is synced after imported'),
            'value' => 'is_synced_after_imported',
        ],
    ]); ?>
</div>

<?php if ($sMedia): ?>

<table class="tablesaw scripto-media" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>#</th>
            <th><?php echo $this->translate('Media'); ?></th>
            <th><?php echo $this->translate('Last synced'); ?></th>
            <th><?php echo $this->translate('Last edited'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($sMedia as $index => $sMedia): ?>
        <tr>
            <td><?php echo $index + 1; ?></td>
            <td>
                <?php echo $sMedia->linkPretty(); ?>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $sMedia->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $this->i18n()->dateFormat($sMedia->synced()); ?></td>
            <td><?php echo $this->i18n()->dateFormat($sMedia->edited()); ?></td>
            <td><?php echo $this->translate($sMedia->status()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>
<div class="no-resources">
    <p><?php echo sprintf(
        $this->translate('No Scripto media found. %s'),
        sprintf(
            '<a href="%s">%s</a>',
            $this->url('admin/scripto-project-id', ['controller' => 'project', 'action' => 'show-actions'], true),
            $this->translate('Do you need to sync the project?')
        )
    ); ?></p>
</div>
<?php endif; ?>
