<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'show'); 
?>

<?php echo $this->pageTitle($this->translate('Review media'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div id="page-actions">
    <?php echo $sItem->link($this->translate('Review item'), 'show', ['class' => 'button']); ?>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ScriptoMedia')->menu(); ?>
</nav>

<?php echo $this->sectionNav([
    'wikitext' => $this->translate('Wikitext'),
    'html' => $this->translate('HTML'),
]); ?>

<div id="wikitext" class="active section">
    <div style="display: flex; justify-content: space-evenly; flex-wrap: wrap;">
        <textarea disabled><?php echo $sMedia->pageWikitext(); ?></textarea>
        <div><?php echo $media->render(); ?></div>
    </div>
</div>

<div id="html" class="section">
    <?php echo $sMedia->pageHtml(); ?>
</div>
