<?php $this->htmlElement('body')->appendAttribute('class', 'show'); ?>

<?php echo $this->pageTitle($this->translate('Review media'), 1, $this->translate('Scripto'), $media->displayTitle()); ?>

<div id="page-actions">
    <?php echo $sItem->link($this->translate('Review item'), 'show', ['class' => 'button']); ?>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ScriptoMedia')->menu(); ?>
</nav>

<p><?php
if ($sMedia->edited()) {
    echo sprintf(
        $this->translate('Last edited on %s by %s'),
        $sMedia->edited()->format('G:i, j F Y'),
        $sMedia->editedBy()
    );
} else {
    echo $this->translate('Not yet edited');
}
?></p>

<div style="display: flex; justify-content: space-evenly; flex-wrap: wrap;">
    <textarea style="flex-grow: 0.80;" disabled><?php echo $sMedia->pageWikitext(); ?></textarea>
    <div><?php echo $media->render(); ?></div>
</div>
