<?php 
$this->headLink()->appendStylesheet($this->assetUrl('css/admin.css', 'Scripto'));
$this->headLink()->appendStylesheet('https://use.fontawesome.com/releases/v5.0.9/css/all.css');
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/admin.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/common/media.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/admin/media-show.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'scripto media show');
?>

<?php echo $this->pageTitle($media->displayTitle(), 1, $this->scripto()->translate($project->mediaType(), 'Scripto: Media'), $this->translate('Notes')); ?>

<?php echo $this->scripto()->adminLoginBar(); ?>

<?php echo $this->scripto()->adminBreadcrumbs(); ?>

<?php echo $this->form()->openTag($mediaForm); ?>
<?php echo $this->formElement($mediaForm->get('mediaform_csrf')); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <?php echo $this->scripto()->watchlistToggle($sMedia); ?>
        <?php echo $this->hyperlink($this->translate('Revision history'), $this->url('admin/scripto-talk-revision', ['action' => 'browse-talk'], true), ['class' => 'button']); ?></li>
        <?php echo $this->formSubmit($mediaForm->get('submit_mediaform')); ?>
    </div>
</div>

<?php echo $this->scripto()->mediaPagination('talk'); ?>

<?php echo $this->sectionNav([
    'wikitext' => $this->translate('Wikitext'),
    'html' => $this->translate('HTML'),
    'media-metadata' => $this->translate('Omeka media metadata'),
]); ?>

<div id="wikitext" class="active section">
<div class="resource-content">
  <div id="media-column" class="wikitext-flex">
      <div class="media render">
          <?php if ($sMedia->isRenderableImage()): ?>
          <?php echo $this->partial('common/media-viewer'); ?>
          <?php else: ?>
          <div class="panzoom-container">
              <?php echo $media->render(['link' => null]); ?>
          </div>
          <?php endif; ?>
      </div>
      <div class="media copy">
        <?php $pageHtml = $sMedia->pageHtml(0); ?>
        <textarea disabled   aria-label="<?php echo $this->translate('Wikitext'); ?>"><?php echo $pageHtml; ?></textarea>
      </div>
      <?php $displayValues = $media->displayValues(); ?>
      <?php if ($displayValues): ?>
      <div class="media metadata">
          <h3><?php echo $this->translate('Metadata'); ?></h3>
          <?php echo $displayValues; ?>
      </div>
      <?php endif; ?>
  </div>
  <div class="notes-column">
      <?php $pageHtml = $sMedia->pageHtml(1); ?>
      <?php echo $pageHtml  ? $pageHtml : sprintf('<span>[%s]</span>', $this->translate('No notes yet.')); ?>
      <ul class="note-actions">
          <li><?php echo $this->hyperlink($this->translate('Browse notes history'), $this->url('admin/scripto-talk-revision', ['action' => 'browse-talk'], true)); ?></li>
      </ul>
  </div>
</div>

</div>

<div id="html" class="section">
      <?php $pageHtml = $sMedia->pageHtml(0); ?>
      <?php echo $pageHtml  ? $pageHtml : sprintf('<span>[%s]</span>', $this->scripto()->translate($project->contentType(), 'No HTML')); ?>
</div>

<div id="media-metadata" class="section">
    <?php
    $resourceClass = $media->resourceClass();
    $values = $media->displayValues();
    ?>
    <?php if ($resourceClass || $values): ?>
    <?php if ($resourceClass): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Class'); ?></h4>
        <div class="value"><?php echo $resourceClass->label(); ?></div>
    </div>
    <?php endif; ?>
    <?php echo $values; ?>
    <?php else: ?>
    <div class="no-resources">
        <p><?php echo $this->translate('The Omeka media has no metadata.'); ?></p>
    </div>
    <?php endif; ?>
</div>

<div class="sidebar always-open" id="reviewer-form">

    <!-- Revision section -->
    <div class="revision meta-group">
        <nav role="navigation" class="pagination">
            <?php if (isset($revision['parentid'])): ?>
            <?php echo $this->hyperlink('', $this->url(null, ['revision-id' => $revision['parentid']], true), ['class' => 'previous o-icon-prev button', 'title' => $this->translate('Older revision')]); ?>
            <?php else: ?>
            <span class="previous o-icon-prev button inactive"></span>
            <?php endif; ?>
            <?php if (isset($revision['childid'])): ?>
            <?php echo $this->hyperlink('', $this->url(null, ['revision-id' => $revision['childid']], true), ['class' => 'next o-icon-next button', 'title' => $this->translate('Newer revision')]); ?>
            <?php else: ?>
            <span class="next o-icon-next button inactive"></span>
            <?php endif; ?>
            <?php if (isset($revision['latestid']) && $revision['latestid'] !== $revision['revid']): ?>
            <?php echo $this->hyperlink('', $this->url(null, ['revision-id' => $revision['latestid']], true), ['class' => 'last o-icon-last button', 'title' => $this->translate('Latest revision')]); ?>
            <?php else: ?>
            <span class="last o-icon-last button inactive"></span>
            <?php endif; ?>
        </nav>
        <h3><?php echo $this->translate('This revision'); ?></h3>
        <?php if ($revision): ?>
            <div class="value">
                <?php echo sprintf(
                    $this->translate('%s: %s by %s'),
                    ($latestRevision && ($latestRevision['revid'] === $revision['revid']))
                        ? sprintf('<span class="green">%s</span>', $this->translate('Latest'))
                        : sprintf('<span class="red">%s</span>', $this->translate('Out-of-date')),
                    $revision['timestamp']->format('G:i, j F Y'),
                    $this->hyperlink($revision['user'], $this->url('admin/scripto-user-contributions', ['user-id' => $revision['user']]))
                ); ?>
                <?php if ($revision['parsedcomment']): ?>
                <div class="parsed-comment"><?php echo $revision['parsedcomment'] ?></div>
                <?php endif; ?>
            </div>
            <?php if ($sMedia->userIsAllowed('review')): ?>
            <?php if ($latestRevision && ($latestRevision['content'] !== $revision['content'])): ?>
            <div class="value">
                <?php echo $this->hyperlink($this->translate('Revert to this revision.'), '#', ['class' => 'sidebar-content', 'data-sidebar-selector' => '#revert-revision']); ?>
            </div>
            <?php endif; ?>
            <?php endif; ?>
        <?php else: ?>
            <div class="value"><?php echo $this->translate('There are no revisions.'); ?></div>
        <?php endif; ?>
    </div>

    <?php if ($sMedia->userCan(1, 'protect')): ?>
    <!-- Protection section -->
    <div class="meta-group">
        <h3><?php echo $this->translate('Edit protection'); ?></h3>
        <div class="field">
            <?php echo $this->formSelect($mediaForm->get('protection_level')); ?>
            <?php echo $this->formSelect($mediaForm->get('protection_expiry')); ?>
        </div>
    </div>
    <?php endif; ?>

</div>

<?php echo $this->form()->closeTag(); ?>

<?php if ($revision): ?>
<div id="revert-revision" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Revert to this revision'); ?></h3>
    <p><?php echo sprintf(
        $this->translate('%s: You are reverting to an out-of-date revision. Any changes made since this revision will be lost, including changes that may be constructive. Note that this revert will not affect which revisions are marked as completed or approved.'),
        sprintf('<span class="red">%s</span>', 'Warning')
    ); ?></p>
    <p><?php echo $this->hyperlink(
        $this->translate('Verify changes before confirming this reversion.'),
        $this->url('admin/scripto-revision-compare', ['action' => null, 'from-revision-id' => $latestRevision['revid'], 'to-revision-id' => $revision['revid']], true),
        ['target' => '_blank']
    ); ?></p>
    <?php echo $this->form($revertForm); ?>
</div>
<?php endif; ?>
