<?php 
$this->headLink()->appendStylesheet($this->assetUrl('vendor/featherlight/featherlight.min.css', 'Scripto'));
$this->headLink()->appendStylesheet($this->assetUrl('css/scripto.css', 'Scripto'));
$this->headLink()->appendStylesheet('https://use.fontawesome.com/releases/v5.0.9/css/all.css');
$this->headScript()->appendFile($this->assetUrl('vendor/jquery-panzoom/jquery.panzoom.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('vendor/featherlight/featherlight.min.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/media-review.js', 'Scripto'));
$this->headScript()->appendFile($this->assetUrl('js/scripto.js', 'Scripto'));
$this->htmlElement('body')->appendAttribute('class', 'scripto media show');
$mediaType = $media->mediaType();
$mediaIsImage = ((strpos($mediaType, 'image')) !== false);
?>

<?php echo $this->pageTitle($media->displayTitle(), 1, $this->translate(sprintf('Scripto: %s', 'Media')), $this->translate('Review')); ?>

<?php echo $this->scripto()->adminLoginBar(); ?>

<?php echo $this->scripto()->adminBreadcrumbs(); ?>

<?php echo $this->form()->openTag($mediaForm); ?>
<?php echo $this->formElement($mediaForm->get('mediaform_csrf')); ?>

<div id="page-actions">
    <div id="page-action-menu">
        <?php if ($this->scripto()->apiClient()->userIsLoggedIn()): ?>
        <?php if ($sMedia->isWatched()): ?>
        <a href="#" class="watchlist button watched" aria-label="<?php echo $this->translate('Stop watching media'); ?>" title="<?php echo $this->translate('Stop watching media'); ?>"></a>
        <?php else: ?>
        <a href="#" class="watchlist button" aria-label="<?php echo $this->translate('Watch media'); ?>" title="<?php echo $this->translate('Watch media'); ?>"></a>
        <?php endif; ?>
        <?php echo $this->formHidden($mediaForm->get('is_watched')); ?>
        <?php endif; ?>
        <?php echo $this->formSubmit($mediaForm->get('submit_mediaform')); ?>
    </div>
</div>

<?php
$previous = $sMedia->previousScriptoMedia();
$next = $sMedia->nextScriptoMedia();
?>
<nav class="pagination" role="navigation">
    <?php if ($previous): ?>
    <?php echo $this->hyperlink('', $previous->adminUrl(), ['class' => 'previous o-icon-prev button', 'title' => $this->translate('Previous')]); ?>
    <?php else: ?>
    <span class="previous o-icon-prev button inactive"></span>
    <?php endif; ?>
    <?php if ($next): ?>
    <?php echo $this->hyperlink('', $next->adminUrl(), ['class' => 'next o-icon-next button', 'title' => $this->translate('Next')]); ?>
    <?php else: ?>
    <span class="next o-icon-next button inactive"></span>
    <?php endif; ?>
    <span class="row-count"><?php echo sprintf($this->translate('%s of %s'), $sMedia->position(), $sMedia->scriptoItem()->mediaCount()); ?></span>
</nav>

<?php echo $this->sectionNav([
    'wikitext' => $this->translate('Wikitext'),
    'html' => $this->translate('HTML'),
    'media-metadata' => $this->translate('Omeka media metadata'),
]); ?>

<div id="wikitext" class="active section">
    <div class="wikitext-featherlight horizontal">
        <h3><?php echo $media->displayTitle(); ?></h3>
        <button class="full-screen"><?php echo $this->translate('Go full screen'); ?></button>
        <div class="layout">
            <label><?php echo $this->translate('Layout'); ?></label>
            <button name="horizontal" class="horizontal active" aria-label="<?php echo $this->translate('Horizontal view'); ?>" title="<?php echo $this->translate('Horizontal view'); ?>" disabled></button>
            <button name="vertical" class="vertical" aria-label="<?php echo $this->translate('Vertical view'); ?>" title="<?php echo $this->translate('Vertical view'); ?>"></button>
        </div>
        <div class="wikitext-flex">
            <div class="textarea-flex">
                <textarea disabled><?php echo $revisionWikitext; ?></textarea>
            </div>
            <div class="panzoom-container <?php echo ($mediaIsImage) ? 'image' : ''; ?>">
                <?php echo $media->render(['link' => null]); ?>
                <?php if ($mediaIsImage): ?>
                <div class="zoom-controls">
                    <button class="zoom-in" aria-label="<?php echo $this->translate('Zoom in'); ?>" title="<?php echo $this->translate('Zoom in'); ?>"></button>
                    <button class="zoom-out" aria-label="<?php echo $this->translate('Zoom out'); ?>" title="<?php echo $this->translate('Zoom out'); ?>"></button>
                    <button class="rotate-right" aria-label="<?php echo $this->translate('Rotate right'); ?>" title="<?php echo $this->translate('Rotate right'); ?>"></button>
                    <button class="rotate-left" aria-label="<?php echo $this->translate('Rotate left'); ?>" title="<?php echo $this->translate('Rotate left'); ?>"></button>
                    <button class="reset"><?php echo $this->translate('Reset'); ?></button>
                </div>
                <?php endif; ?>
            </div>
        </div>
        <?php if ($mediaIsImage): ?>
        <script>
        (function($) {
            var $zoomContainer = $('.panzoom-container');
            $('#wikitext .media-render').panzoom({
                $zoomIn: $zoomContainer.find(".zoom-in"),
                $zoomOut: $zoomContainer.find(".zoom-out"),
                $reset: $zoomContainer.find(".reset")
            });
        })(jQuery);
        </script>
        <?php endif; ?>
    </div>
</div>

<div id="html" class="section">
    <?php echo $revisionHtml; ?>
</div>

<div id="media-metadata" class="section">
    <?php
    $resourceClass = $media->resourceClass();
    $values = $media->displayValues();
    ?>
    <?php if ($resourceClass || $values): ?>
    <?php if ($resourceClass): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Class'); ?></h4>
        <div class="value"><?php echo $resourceClass->label(); ?></div>
    </div>
    <?php endif; ?>
    <?php echo $values; ?>
    <?php else: ?>
    <div class="no-resources">
        <p><?php echo $this->translate('The Omeka media has no metadata.'); ?></p>
    </div>
    <?php endif; ?>
</div>

<div class="sidebar always-open" id="reviewer-form">

    <!-- Revision section -->
    <?php if ($revision): ?>
    <h3>
        <?php if ($revision['latestid'] === $revision['revid']): ?>
        <?php echo $this->translate('Revision — latest'); ?>
        <?php else: ?>
        <?php echo $this->translate('Revision — out-of-date'); ?>
        <?php endif; ?>
    </h3>
    <nav>
        <?php if ($revision['parentid']): ?>
        <?php echo $this->hyperlink('', $this->url(null, ['revision-id' => $revision['parentid']], true), ['class' => 'previous o-icon-prev button', 'title' => $this->translate('Older revision')]); ?>
        <?php else: ?>
        <span class="previous o-icon-prev button inactive"></span>
        <?php endif; ?>
        <?php if ($revision['childid']): ?>
        <?php echo $this->hyperlink('', $this->url(null, ['revision-id' => $revision['childid']], true), ['class' => 'next o-icon-next button', 'title' => $this->translate('Newer revision')]); ?>
        <?php else: ?>
        <span class="next o-icon-next button inactive"></span>
        <?php endif; ?>
        <?php if ($revision['latestid'] && $revision['latestid'] !== $revision['revid']): ?>
        <?php echo $this->hyperlink('', $this->url(null, ['revision-id' => $revision['latestid']], true), ['class' => 'next o-icon-last button', 'title' => $this->translate('Latest revision')]); ?>
        <?php else: ?>
        <span class="next o-icon-last button inactive"></span>
        <?php endif; ?>
    </nav>
    <div class="meta-group">
        <div class="revision-timestamp">
            <?php echo sprintf(
                $this->translate('%s by %s.'),
                $revision['timestamp']->format('G:i:s, j F Y'),
                $this->hyperlink($revision['user'], $this->url('admin/scripto-user-contributions', ['user-id' => $revision['user']]))
            ); ?>
        </div>
        <?php if ($revision['parsedcomment']): ?>
        <div class="parsed-comment"><?php echo $revision['parsedcomment'] ?></div>
        <?php endif; ?>
        <div><?php echo $this->hyperlink($this->translate('View revision history'), $this->url('admin/scripto-revision', ['action' => 'browse'], true), ['class' => 'button']); ?></div>
        <?php if (($latestRevision['revid'] !== $revision['revid']) && ($latestRevision['content'] !== $revision['content'])): ?>
        <div><?php echo $this->hyperlink($this->translate('Revert to this revision'), '#', ['class' => 'sidebar-content button', 'data-sidebar-selector' => '#revert-revision']); ?></div>
        <?php endif; ?>
    </div>
    <?php else: ?>
    <h3><?php echo $this->translate('Revision'); ?></h3>
    <div class="meta-group">
        <?php echo $this->translate('There are no revisions.'); ?>
    </div>
    <?php endif; ?>

    <!-- Review section -->
    <h3><?php echo $this->translate('Review media'); ?></h3>
    <div class="review-fields">
        <?php
        $completed = $sMedia->completed();
        $completedBy = $sMedia->completedBy();
        ?>
        <div class="field">
            <label for="is_completed"><?php echo $this->translate('Completed'); ?></label>
            <?php echo $this->formCheckbox($mediaForm->get('is_completed')); ?>
            <?php if ($completed): ?>
            <div>
                <?php echo sprintf(
                    $this->translate('Last completed %s by %s'),
                    $this->i18n()->dateFormat($completed, 'medium', 'short'),
                    $this->hyperlink($completedBy, $this->url('admin/scripto-user-contributions', ['user-id' => $completedBy]))
                ); ?>
            </div>
            <?php endif; ?>
        </div>
        <?php if ($sMedia->userCan('protect')): ?>
        <div class="field">
            <label for="protection_level"><?php echo $this->translate('Protection'); ?></label>
            <?php echo $this->formSelect($mediaForm->get('protection_level')); ?>
            <?php echo $this->formSelect($mediaForm->get('protection_expiry')); ?>
        </div>
        <?php endif; ?>
        <?php
        $approved = $sMedia->approved();
        $approvedBy = $sMedia->approvedBy();
        ?>
        <div class="field">
            <label for="is_approved"><?php echo $this->translate('Approved'); ?></label>
            <?php echo $this->formCheckbox($mediaForm->get('is_approved')); ?>
            <?php if ($approved): ?>
            <div>
                <?php echo sprintf(
                    $this->translate('Last approved %s by %s'),
                    $this->i18n()->dateFormat($approved, 'medium', 'short'),
                    $approvedBy
                        ? $approvedBy->link($approvedBy->name())
                        : $this->translate('Unknown')
                    ); ?>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <!-- Metadata section -->
    <?php echo $this->partial('show-details'); ?>
</div>

<?php echo $this->form()->closeTag(); ?>

<div id="revert-revision" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Revert to this revision'); ?></h3>
    <p class="error"><?php echo $this->translate('Warning: You are reverting to an out-of-date revision. Any changes made since this revision will be lost.'); ?></p>
    <?php echo $this->form($revertForm); ?>
</div>
